<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>
<ul class="add-to-links">
	<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()):
	   $wlid = (int) $this->getRequest()->getParam('wlid');
	?>
		<?php if($wlid > 0){ ?>
			<li><a href="<?php echo Mage::getBaseUrl().'gwishlist/gwishlist/updategwishlist'; ?>/item/<?php echo $wlid; ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Update') ?></a></li>
		<?php } else { ?>
 			<li><a href="<?php echo Mage::getBaseUrl().'gwishlist/gwishlist/add'; ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><span class="hidden-md hidden-lg"><?php echo $this->__('Wishlist') ?></span><span class="hidden-xs hidden-sm"><?php echo $this->__('Add to Wishlist') ?></span></a></li>
	 	<?php } ?>
	 <?php else: ?>
		<?php if ($this->helper('wishlist')->isAllow()) : ?>
			<li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
		<?php endif; ?>
	<?php endif; ?>
</ul>
