<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<div class="category-no-results">
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('category_no_results')->toHtml() ?>
</div>
<?php else: ?>
<div class="category-products">
    <div class="toolbar-top">
        <?php echo $this->getToolbarHtml() ?>
    </div>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?> <?php if ($_product->isGrouped()): ?>item-grouped<?php endif; ?>">
            <div class="item-box">
                <?php // Product Image ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(420); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
                <?php // Product description ?>
                <div class="product-shop">
                    <div class="product-info">
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                        <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product) ?>
                        <?php endif; ?>

                        <?php if ($_product->isGrouped()):
                            $_associatedProducts = $_product->getTypeInstance(true)->getAssociatedProducts($_product); 
                            $prices = [];
                            $grouped_price = 0;
                            $price_difference = 0;

                            foreach($_associatedProducts as $_item) {
                                $id = $_item->getId();
                                $product = Mage::getModel('catalog/product')->load($id);

                                $prices[] = $product['price'];

                                if ($product['special_price']) {
                                    $grouped_price += $product['special_price'];
                                    $price_difference += $product['price']-$product['special_price'];
                                    $old_price = $grouped_price + $price_difference;
                                } else {
                                    $grouped_price += $product['price'];
                                }
                            }

                            arsort($prices); // get highest price
                            $price_array = array_keys($prices);
                            $highest_price = $prices[$price_array[0]];
                        ?>

                            <?php //echo $this->__('Highest price:') ?>
                            <?php //echo Mage::helper('core')->currency($highest_price) ?>

                            <div class="price-box">
                                <span class="regular-price">
                                    <?php //echo $this->__('Total price for all these products:') ?>
                                    <span class="price"><?php echo Mage::helper('core')->currency($grouped_price) ?></span>
                                </span>
                            </div>

                            <?php //if ($price_difference): ?>
                                <?php //echo $this->__('Total save with all these products:') ?>
                                <?php //echo Mage::helper('core')->currency($price_difference) ?>
                            <?php //endif; ?>

                        <?php else: ?>
                            <?php echo $this->getPriceHtml($_product, true); ?>
                        <?php endif; ?>

                        <?php if ($_product->isGrouped()):
                            $_finalPrice  = $grouped_price; else:
                            $_finalPrice  = $_product->getFinalPrice();
                        endif; ?>

                        <ul class="price-new">
                            <?php
                                $_plots = $_product->getData('price_plots');
                                $_plots_tax = $_product->getData('plots_tax');
                                if($_plots != ""):
                            ?>
                                <li class="price-plots-block">
                                    <?php echo '<strong> '.$_plots .'x '.$this->__('of').' '.$this->helper('core')->currency(($_finalPrice * $_plots_tax) + $_finalPrice / $_plots, true, false).' '.$this->__('interest-free').'</strong>' ?>
                                </li>
                            <?php endif; ?>
                            <?php
                                $_barcode     = $_product->getData('discount_barcode');
                                $_calcBarcode = ($_barcode / 100) * $_finalPrice;
                                $_calcFinal   = $this->helper('core')->currency($_finalPrice - $_calcBarcode, true, false);
                                if($_barcode != ""):
                            ?>
                                <li class="price-barcode-block">
                                    <strong class="barcode-price-label"><?php echo $_barcode.'% '.' off '.$this->__('via barcode');  ?></strong>
                                    <span class="special-price barcode-price"><span class="price"><?php echo $_calcFinal; ?></span></span>
                                </li>
                            <?php endif; ?>
                        </ul>

                        <div class="desc std">
                            <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                        </div>
                    </div>
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>
                            <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php echo Mage::helper('netgo_gwishlist')->getUrl($_product); ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><a href="<?php echo $_compareUrl ?>" class="link-compare" data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>
    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
        <ul class="products-grid">
        <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php //if ($i++%$_columnCount==0): ?>
        <?php //endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> <?php if ($_product->isGrouped()): ?>item-grouped<?php endif; ?>">
                <div class="item-box">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(420); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <div class="item-wrap">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>

                        <?php if($_product->getRatingSummary()): ?>
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short'); ?>
                        <?php endif; ?>

                        <?php if ($_product->isGrouped()):
                            $_associatedProducts = $_product->getTypeInstance(true)->getAssociatedProducts($_product);
                            $prices = [];
                            $grouped_price = 0;
                            $price_difference = 0;

                            foreach($_associatedProducts as $_item) {
                                $id = $_item->getId();
                                $product = Mage::getModel('catalog/product')->load($id);
                                $prices[] = $product['price'];

                                if ($product['special_price']) {
                                    $grouped_price += $product['special_price'];
                                    $price_difference += $product['price']-$product['special_price'];
                                    $old_price = $grouped_price + $price_difference;
                                } else {
                                    $grouped_price += $product['price'];
                                    $old_price += $product['price'];
                                }
                            }

                            arsort($prices); // get highest price
                            $price_array = array_keys($prices);
                            $highest_price = $prices[$price_array[0]]; 
                        ?>

                            <?php //echo $this->__('Highest price:') ?>
                            <?php //echo Mage::helper('core')->currency($highest_price) ?>

                            <div class="price-box">
                                <span class="regular-price">
                                    <span class="price"><?php echo Mage::helper('core')->currency($grouped_price); ?></span>
                                </span>
                                <?php if ($old_price): ?>
                                    <span class="old-price">
                                        <span class="price"><?php echo Mage::helper('core')->currency($old_price); ?></span>
                                    </span>
                                <?php endif; ?>
                            </div>

                            <?php //if ($price_difference): ?>
                                <?php //echo $this->__('Total save with all these products:') ?>
                                <?php //echo Mage::helper('core')->currency($price_difference) ?>
                            <?php //endif; ?>

                        <?php else: ?>
                            <?php echo $this->getPriceHtml($_product, true); ?>
                        <?php endif; ?>

                        <?php if ($_product->isGrouped()):
                            $_finalPrice  = $grouped_price; else:
                            $_finalPrice  = $_product->getFinalPrice();
                        endif; ?>

                        <ul class="price-new">
                            <?php
                                $_plots = $_product->getData('price_plots');
                                $_plots_tax = $_product->getData('plots_tax');
                                if($_plots != ""):
                            ?>
                                <li class="price-plots-block">
                                    <?php echo '<strong> '.$_plots .'x '.$this->__('of').' '.$this->helper('core')->currency(($_finalPrice * $_plots_tax) + $_finalPrice / $_plots, true, false).' '.$this->__('interest-free').'</strong>' ?>
                                </li>
                            <?php endif; ?>
                            <?php
                                $_barcode     = $_product->getData('discount_barcode');
                                $_calcBarcode = ($_barcode / 100) * $_finalPrice;
                                $_calcFinal   = $this->helper('core')->currency($_finalPrice - $_calcBarcode, true, false);
                                if($_barcode != ""):
                            ?>
                                <li class="price-barcode-block">
                                    <strong class="barcode-price-label"><?php echo $_barcode.'% '.' off '.$this->__('via barcode');  ?></strong>
                                    <span class="special-price barcode-price"><span class="price"><?php echo $_calcFinal; ?></span></span>
                                </li>
                            <?php endif; ?>
                        </ul>

                        <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <ul class="add-to-links">
                                <?php echo Mage::helper('netgo_gwishlist')->getUrl($_product); ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li><a href="<?php echo $_compareUrl ?>" class="link-compare" data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </li>
            <?php //if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            <?php //endif ?>
            <?php endforeach ?>
        </ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
