<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="product-shop">
            <?php echo $this->getBlockHtml('formkey') ?>
            
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <div class="product-sku">
                <span><?php echo $this->__('SKU') ?>:</span> <?php echo $_product->getData('sku'); ?></span>
            </div>

            <div class="product-name">
                <?php $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                <h1><span><?php echo $_productName ?></span></h1>
            </div>

            <div class="row clean middle-xs between-xs">
                <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>

                <?php if ($this->canEmailToFriend()): ?>
                    <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
                <?php endif; ?>
            </div>

            <?php echo $this->getChildHtml('alert_urls') ?>

            <?php echo $this->getChildHtml('product_type_data') ?>

            <?php if ($_product->isGrouped()):
                $_associatedProducts = $_product->getTypeInstance(true)->getAssociatedProducts($_product);
                $prices = [];
                $grouped_price = 0;
                $price_difference = 0;

                foreach($_associatedProducts as $_item) {
                    $id = $_item->getId();
                    $product = Mage::getModel('catalog/product')->load($id);
                    $prices[] = $product['price'];

                    if ($product['special_price']) {
                        $grouped_price += $product['special_price'];
                        $price_difference += $product['price']-$product['special_price'];
                        $old_price = $grouped_price + $price_difference;
                    } else {
                        $grouped_price += $product['price'];
                        $old_price += $product['price'];
                    }
                }

                arsort($prices); // get highest price
                $price_array = array_keys($prices);
                $highest_price = $prices[$price_array[0]]; 
            ?>

                <?php //echo $this->__('Highest price:') ?>
                <?php //echo Mage::helper('core')->currency($highest_price) ?>

                <div class="price-box">
                    <div class="price-box-legend">
                        <small><span><?php echo $this->__('Total price for all these products:') ?></span></small>
                    </div>

                    <span class="regular-price">
                        <span class="price"><?php echo Mage::helper('core')->currency($grouped_price - $price_difference); ?></span>
                    </span>

                    <?php if ($old_price): ?>
                        <?php if ($old_price != $grouped_price): ?>
                            <span class="old-price">
                                <span class="price"><?php echo Mage::helper('core')->currency($old_price); ?></span>
                            </span>
                        <?php endif; ?>
                    <?php endif; ?>

                    <?php if ($price_difference): ?>
                        <div class="price-box-diff">
                            <small><span><?php echo $this->__('Total save with all these products:') ?></span></small>
                            <span class="special-price">
                                <span class="price"><?php echo Mage::helper('core')->currency($price_difference); ?></span>
                            </span>
                        </div>
                    <?php endif; ?>
                </div>

                

            <?php else: ?>
                <?php echo $this->getTierPriceHtml() ?>
            <?php endif; ?>

            <?php if ($_product->isGrouped()):
                $_finalPrice  = $grouped_price; else:
                $_finalPrice  = $_product->getFinalPrice();
            endif; ?>

            <ul class="price-new">
                <?php
                    $_plots = $_product->getData('price_plots');
                    $_plots_tax = $_product->getData('plots_tax');
                    if($_plots != ""):
                ?>
                <li class="price-plots-block">
                    <div class="simple-collapse cc-collapse">
                        <div class="collapse-title">
                            <div class="row middle-xs between-xs">
                                <div class="col-xs">
                                    <?php echo $this->__('Max plots').' <strong>'.$_plots.'x '.$this->__('interest-free').'</strong>' ?>
                                </div>
                                <div class="col-xs-6 text-right">
                                    <?php //echo $this->__('View plots') ?>
                                    <div>
                                        <span class="visa" data-toggle="tooltip" title="Visa">
                                            <span class="pf pf-visa"><span class="sr-only"><?php echo $this->__('Visa') ?></span></span>
                                        </span>
                                        <span class="mastercard" data-toggle="tooltip" title="Mastercard">
                                            <span class="pf pf-mastercard"><span class="sr-only"><?php echo $this->__('Mastercard') ?></span></span>
                                        </span>
                                        </span>
                                        <span class="elo" data-toggle="tooltip" title="Elo">
                                            <span class="pf pf-elo"><span class="sr-only"><?php echo $this->__('Elo') ?></span></span>
                                        </span>
                                        <span class="hipercard" data-toggle="tooltip" title="Hipercard">
                                            <span class="pf pf-hipercard"><span class="sr-only"><?php echo $this->__('Hipercard') ?></span></span>
                                        </span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="collapse-content">
                            <ul class="table table-striped">
                                <li><strong>1x</strong> <?php echo $this->__('of') . ' ' . $this->helper('core')->currency($_finalPrice, true, false) ?></li>
                                <?php for ($i = 2; $i <= $_plots; $i++ ) {
                                    echo '<li><strong>' . $i . 'x</strong> ' . $this->__('of') . ' ' . $this->helper('core')->currency(($_finalPrice * $_plots_tax) + $_finalPrice / $i, true, false) . ' ' . $this->__('') . '</li>';
                                } ?>
                            </ul>
                        </div>
                    </div>
                </li>
                <?php endif;?>
                <?php
                    $_barcode     = $_product->getData('discount_barcode');
                    $_calcBarcode = ($_barcode / 100) * $_finalPrice;
                    $_calcFinal   = $this->helper('core')->currency($_finalPrice - $_calcBarcode, true, false);
                    if($_barcode != ""):
                ?>
                <li class="price-barcode-block">
                    <div class="simple-collapse">
                        <div class="collapse-title">
                            <div class="row middle-xs between-xs">
                                <div class="col-xs-10 row clean middle-xs">
                                    <strong class="barcode-price-label"><?php echo $_barcode . '% ' . $this->__('of') . ' ' . $this->__('discount via barcode');  ?></strong>
                                    <span class="special-price barcode-price"><span class="price"><?php echo $_calcFinal; ?></span></span>
                                </div>

                                <div class="col-xs-2 text-right">
                                    <div>
                                        <span class="barcode" data-toggle="tooltip" title="<?php echo $this->__('Barcode'); ?>">
                                            <span class="fa fa-barcode"><span class="sr-only"><?php echo $this->__('Barcode'); ?></span></span>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="collapse-content">
                            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('barcode_instructions')->toHtml() ?>
                        </div>
                    </div>
                </li>
                <?php endif;?>
            </ul>

            <?php echo $this->getChildHtml('extrahint') ?>

            <?php echo $this->getChildHtml('shipping.estimate.form') ?>

            <?php if ($_product->getShortDescription()):?>
                <div class="short-description">
                    <h2><?php echo $this->__('Quick Overview') ?></h2>
                    <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                </div>
            <?php endif;?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>

            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

            <div class="row between-xs">
                <div class="col-xs-5">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>

                <div class="col-xs">
                    <?php $currentUrl = Mage::helper('core/url')->getCurrentUrl() ?>
                    <div class="sharer-list">
                        <strong class="hidden"><?php echo $this->__("Share:") ?></strong>
                        <ul>
                            <li class="sharer-twitter">
                                <a 
                                    class="sharer" 
                                    href="javascript:void(0)"
                                    data-sharer="twitter" 
                                    data-width="800" 
                                    data-height="600" 
                                    data-title="<?php echo $_productName ?>" 
                                    data-url="<?php echo $currentUrl ?>"
                                    <?php // data-via="" data-hashtags=""?>
                                    data-toggle="tooltip"
                                    title="Compartilhar no Twitter">
                                    <span>Twitter</span></a>
                            </li>
                            <li class="sharer-facebook">
                                <a 
                                    class="sharer" 
                                    href="javascript:void(0)"
                                    data-sharer="facebook" 
                                    data-width="800" 
                                    data-height="600" 
                                    data-url="<?php echo $currentUrl ?>"
                                    data-toggle="tooltip"
                                    title="Compartilhar no Facebook">
                                    <span>Facebook</span></a>
                            </li>
                            <li class="sharer-pinterest hidden-xs">
                                <a 
                                    class="sharer" 
                                    href="javascript:void(0)"
                                    data-sharer="pinterest" 
                                    data-width="800" 
                                    data-height="600" 
                                    data-url="<?php echo $currentUrl ?>" 
                                    data-image="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(1200) ?>" 
                                    data-description="<?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?>"
                                    data-toggle="tooltip"
                                    title="Compartilhar no Pinterest">
                                    <span>Pinterest</span></a>
                            </li>
                            <li class="sharer-whatsapp hidden-sm hidden-md hidden-lg">
                                <a 
                                    class="sharer" 
                                    href="javascript:void(0)"
                                    data-sharer="whatsapp" 
                                    data-width="800" 
                                    data-height="600" 
                                    data-title="<?php echo $_productName ?>" 
                                    data-url="<?php echo $currentUrl ?>"
                                    data-toggle="tooltip"
                                    title="Enviar no WhatsApp">
                                    <span>WhatsApp</span></a>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
            
        </div>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="clearer"></div>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>

    <div class="product-content">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-5 col-lg-5">
                <?php echo $this->getChildHtml('product.attributes') ?>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-7 col-lg-7">
                <?php
                    $_video = $_product->getData('video');
                    if($_video != ""):
                ?>
                    <h2><?php echo $this->__("Video") ?></h2>
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="<?php echo 'https://www.youtube.com/embed/' . $_video ?>"></iframe>
                    </div>
                <?php endif ?>

                <?php echo $this->getChildHtml('product.description') ?>

                <div class="product-collateral toggle-content tabs">
                    <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
                        <dl id="collateral-tabs" class="collateral-tabs">
                            <?php foreach ($detailedInfoGroup as $alias => $html):?>
                                <?php //echo $this->escapeHtml($this->getChildData($alias, 'title')) ?>
                                <div class="tab-content"><?php echo $html ?></div>
                            <?php endforeach;?>
                        </dl>
                    <?php endif; ?>
                </div>


            </div>
        </div>
    </div>

    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
</div>
