<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <div class="col-xs-12 my-wishlist">
        <?php echo $this->getMessagesBlock()->toHtml() ?>
        <?php echo $this->getChildHtml('top'); ?>
        <div class="page-title title-buttons">
            <h1><?php echo $this->getTitle(); ?></h1>
            <div class="buttons-set">
                <form id="wishlist-view-form" action="<?php echo $this->getUrl('*/*/update', array('wishlist_id' => $this->getWishlistInstance()->getId())) ?>" method="post">
                    <?php if ($this->helper('wishlist')->isRssAllow() && $this->hasWishlistItems()): ?>
                        <a href="<?php echo $this->helper('wishlist')->getRssUrl($this->getWishlistInstance()->getId()); ?>" class="link-rss"><?php echo $this->__('RSS Feed') ?></a>
                    <?php endif; ?>
                    <?php if ($this->hasWishlistItems()): ?>
                        <?php echo $this->getChild('control_buttons')->toHtml();?>
                    <?php endif; ?>
                </form>
            </div>
        </div>

        <div class="wishlist-list">
            <?php if ($this->hasWishlistItems()): ?>
                <?php echo $this->getBlockHtml('formkey');?>
                <?php $this->getChild('items')->setItems($this->getWishlistItems()); ?>
                <?php echo $this->getChildHtml('items');?>
                <script type="text/javascript">decorateTable('wishlist-table')</script>
            <?php else: ?>
                <p class="wishlist-empty"><?php echo $this->__('You have no items in your wishlist.') ?></p>
            <?php endif ?>
        </div>
    
        <form id="wishlist-allcart-form" action="<?php echo $this->getUrl('*/*/allcart') ?>" method="post">
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="wishlist_id" id="wishlist_id" value="<?php echo $this->getWishlistInstance()->getId() ?>" />
                <input type="hidden" name="qty" id="qty" value="" />
            </div>
        </form>

        <script type="text/javascript">
        //<![CDATA[
            var wishlistForm = new Validation($('wishlist-view-form'));
            var wishlistAllCartForm = new Validation($('wishlist-allcart-form'));

            function calculateQty() {
                var itemQtys = new Array();
                $$('#wishlist-view-form .qty').each(
                    function (input, index) {
                        var idxStr = input.name;
                        var idx = idxStr.replace( /[^\d.]/g, '' );
                        itemQtys[idx] = input.value;
                    }
                );

                $$('#qty')[0].value = JSON.stringify(itemQtys);
            }

            function addAllWItemsToCart() {
                calculateQty();
                wishlistAllCartForm.form.submit();
            }
        //]]>
        </script>
    </div>
    <?php echo $this->getChildHtml('bottom'); ?>
<?php endif ?>
