<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="col-xs-12 col-sm-8 col-md-9 col-lg-9">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

    <?php if($this->getTitle()): ?>
        <div class="page-title text-left">
            <h1><?php echo $this->getTitle() ?></h1>
        </div>
    <?php endif; ?>

    <form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
        <?php echo $this->getBlockHtml('formkey')?>
        <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
        <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <h2 class="legend"><?php echo $this->__('Contact Information') ?></h2>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getNameBlockHtml() ?>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Fax') ?></label>
                        <div class="input-box">
                            <input type="text" name="telephone" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text  <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="telephone" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="fax"><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('fax') ?>" />
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Address') ?></h2>
            <ul class="form-list row">
                <li class="col-xs-6">
                    <div class="form-group">
                        <label for="zip" class="required">
                            <em>*</em><?php echo $this->__('Zip/Postal Code') ?>
                        </label>
                        <div class="input-box input-group">
                            <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="postcode" id="postcode" class="input-text form-control validate-number <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>" maxlength="8" onblur="buscaCep('billing');" />
                            <div class="onestepcheckout-postcod-process onestepcheckout-overlay-16">&nbsp;</div>
                            <span class="input-group-btn">
                                <button class="btn btn-default" onclick="popWin('http://www.buscacep.correios.com.br/sistemas/buscacep/', 'I forgot my zipcode', 'width=360,height=370,left=200,top=50,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" type="button" data-toggle="tooltip" title="Qual o meu CEP?"><span class="fa fa-question"></span></button>
                            </span>
                        </div>
                    </div>
                </li>
                <li class="col-xs-6">
                    <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="input-box">
                        <?php echo $this->getCountryHtmlSelect('billing') ?>
                    </div>
                </li>

                <?php ## Street ?>
                <li class="col-xs-12">
                    <div class="row">
                    <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                    <?php $streetValues = $this->getDataFromSession('street'); ?>
                        <div class="col-xs-8">
                            <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Street Address') ?>" name="street[]" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" value="<?php echo (isset($streetValues[0])) ? $streetValues[0] : ''; ?>" autocomplete="off"/>
                            </div>
                        </div>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <div class="wide <?php switch ($_i) {
                                case 2: echo "col-xs-4"; break;
                                case 3: echo "col-xs-6"; break;
                                case 4: echo "col-xs-6"; break; }?>">
                            <label for="street<?php echo $_i ?>" <?php if ($_i != 3): ?> class="required" <?php endif; ?>><?php if ($_i != 3): ?> <em>*</em> <?php endif; ?><?php echo $this->__('Street Address ' . $_i) ?></label>
                            <div class="input-box">
                                <input type="text" title="<?php echo $this->__('Street Address ' . $_i) ?>" name="street[<?php echo $_i ?>]" id="street<?php echo $_i ?>" class="input-text <?php if ($_i != 3): ?>required-entry<?php endif; ?>" value="<?php echo $streetValues[$_i]; ?>" autocomplete="off"/>
                            </div>
                        </div>
                    <?php endfor; ?>
                    </div>
                </li>

                <?php if (Mage::helper('onestepcheckout/config')->isCompany()): ?>
                <li class="col-xs">
                    <label for="company"><?php echo $this->__('Company') ?></label>
                    <div class="input-box">
                        <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                    </div>
                </li>
                <?php endif; ?>

                <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                <li class="col-xs">
                    <label for="vat_id"><?php echo $this->__('VAT Number') ?></label>
                    <div class="input-box">
                        <input type="text" name="vat_id" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" id="vat_id" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
                    </div>
                </li>
                <?php endif; ?>

                <li class="col-xs-6">
                    <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                    </div>
                </li>
                <li class="col-xs-6">
                    <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="input-box">
                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                        //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" />
                    </div>
                </li>
                <li class="col-xs-12">
                    <div<?php if($this->canSetAsDefaultBilling()) echo ' class="control"' ?>>
                        <?php if($this->isDefaultBilling()): ?>
                            <strong><?php echo $this->__('Default Billing Address') ?></strong>
                        <?php elseif($this->canSetAsDefaultBilling()): ?>
                            <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo $this->__('Use as My Default Billing Address') ?>" class="checkbox" /><label for="primary_billing"><?php echo $this->__('Use as my default billing address') ?></label>
                        <?php else: ?>
                            <input type="hidden" name="default_billing" value="1" />
                        <?php endif; ?>
                    </div>
                    <div<?php if($this->canSetAsDefaultShipping()) echo ' class="control"' ?>>
                        <?php if($this->isDefaultShipping()): ?>
                            <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                        <?php elseif($this->canSetAsDefaultShipping()): ?>
                            <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as My Default Shipping Address') ?>" class="checkbox" /><label for="primary_shipping"><?php echo $this->__('Use as my default shipping address') ?></label>
                        <?php else: ?>
                            <input type="hidden" name="default_shipping" value="1" />
                        <?php endif; ?>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button data-action="save-customer-address" type="submit" title="<?php echo $this->__('Save Address') ?>" class="button"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
        </div>
    </form>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
    Validation.add('validate-zip-br', '<?php echo $this->__('Please enter a valid zip code. e.g. 12345678.') ?>', function(v) {
        return Validation.get('IsEmpty').test(v) || /(^\d{8}$)|(^\d{5}-\d{3}$)/.test(v);
    });
    Validation.add('validate-phone-br', '<?php echo $this->__('Please enter a valid phone number. for example, (xx) x4567-8900.') ?>', function(v) {
        return Validation.get('IsEmpty').test(v) || /^(\()?\d{2}(\))?(-|\s)?\d{5}(-|\s)\d{4}|(\()?\d{2}(\))?(-|\s)?\d{4}(-|\s)\d{4}$/.test(v);
    });
    if (jQuery('#telephone')) {
        jQuery('#telephone').addClass('validate-phone-br');
        jQuery('#telephone').on('keyup', function() {
            this.maxLength = 15;
            mascara(this, mtel);
        });
    }
    if (jQuery('#fax')) {
        jQuery('#fax').addClass('validate-phone-br');
        jQuery('#fax').on('keyup', function() {
            this.maxLength = 15;
            mascara(this, mtel);
        });
    }
    if (jQuery('#postcode')) {
        jQuery('#postcode').addClass('validate-zip-br');
        jQuery('#postcode').on('keyup', function() {
            this.maxLength = 8;
            mascara(this, sonumeros);
        });
    }
    if (jQuery('#street_1')) {
        jQuery('#street_1').on('keyup', function() {
            this.maxLength = 40;
        });
    }
    if (jQuery('#street_2')) {
        jQuery('#street_2').on('keyup', function() {
            this.maxLength = 5;
        });
    }
    if (jQuery('#street_3')) {
        jQuery('#street_3').on('keyup', function() {
            this.maxLength = 20;
        });
    }
    if (jQuery('#street_4')) {
        jQuery('#street_4').on('keyup', function() {
            this.maxLength = 20;
        });
    }
    if (jQuery('#city')) {
        jQuery('#city').on('keyup', function() {
            this.maxLength = 30;
        });
    }
//]]>
</script>
<script type="text/javascript">
if(!BASE_URL) var BASE_URL = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>";
</script>
