<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php if(count($this->getStores())>1): ?>
<div class="language">
	<div class="language-switcher">
	    <?php foreach ($this->getStores() as $_lang): ?>
	    	<?php $_active = ($_lang->getId() == $this->getCurrentStoreId()) ? ' class="active"' : '' ?>
	        <a href="<?php echo $_lang->getCurrentUrl() ?>" title="<?php echo $this->htmlEscape($_lang->getName()) ?>" <?php echo $_active ?> data-toggle="tooltip" data-placement="bottom">
	        	<span><span class="flag-icon flag-icon-<?php echo $this->htmlEscape($_lang->getCode()) ?>"></span></span>
	            <strong><span><span><?php echo $this->htmlEscape($_lang->getName()) ?></span></span></strong>
	        </a>
	    <?php endforeach; ?>
	</div>
</div>
<?php endif; ?>
