<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php $blockNumber = $this->getBlockNumber(); ?>
<?php $blockNumberClass = (!is_null($blockNumber)) ? "onestepcheckout-number-{$blockNumber}" : ""; ?>
<?php if(Mage::getStoreConfig('onestepcheckout/general/is_show_titles')): ?>
    <div class="step-title">
        <span class="number onestepcheckout-number <?php echo $blockNumberClass; ?>"><?php echo $blockNumber; ?></span>
        <h2><?php echo $this->__('Payment Method'); ?></h2>
    </div>
<?php endif; ?>
<div class="step a-item">
    <div id="onestepcheckout-payment-method" class="onestepcheckout-add-loader-into-this-block">
        <?php echo $this->getEnterpriseRewardHtml(); ?>
        <div class="sp-methods" id="checkout-payment-method-load">
            <?php $methods = $this->getMethods(); ?>
            <?php $oneMethod = count($methods) <= 1; ?>
            <?php foreach ($methods as $_method): ?>
                <?php $_code = $_method->getCode(); ?>
                <dt class="single-method" rel="<?php echo $_code ?>">
                <?php if (!$oneMethod): ?>
                    <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>"<?php if ($this->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?> class="radio" />
                <?php else: ?>
                    <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
                    <?php $oneMethod = $_code; ?>
                <?php endif; ?>
                <label for="p_method_<?php echo $_code ?>">
                    <?php echo $this->escapeHtml($this->getMethodTitle($_method)) ?> 
                    <?php echo $this->getMethodLabelAfterHtml($_method) ?>
                    <span class="payment-subtitle p_method_<?php echo $_code ?>">
                        <?php if ($_code == 'banktransfer' || $_code == 'cashondelivery'): ?>
                            <?php $_paymentCash = Mage::getStoreConfig('design/advanced_payment/payment_cash_discount'); ?>
                            <strong><?php echo $_paymentCash . $this->__('% off') ?></strong>
                        <?php else: ?>
                            <?php $_paymentPlots = Mage::getStoreConfig('design/advanced_payment/payment_plots'); ?>
                            <?php $_paymentFreePlots = Mage::getStoreConfig('design/advanced_payment/payment_free_plots'); ?>
                            <?php $_paymentShow = Mage::getStoreConfig('design/advanced_payment/payment_plots_show'); ?>
                            <?php  if ($_paymentFreePlots) {
                                $_paymentTax = $this->__('no tax'); } else {
                                $_paymentTax = $this->__('on credit card'); } 
                            ?>
                            <?php if ($_paymentPlots): ?>
                                <span><?php echo $_paymentShow . 'x ' . $_paymentTax; ?></span>
                            <?php endif ?>
                        <?php endif ?>
                    </span>
                </label>
                </dt>
            <?php endforeach; ?>
        </div>
        <?php foreach ($methods as $_method): ?>
                <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
                    <dd>
                        <?php echo $html; ?>
                    </dd>
                <?php endif; ?>
            <?php endforeach; ?>
        <div class="validation-advice" style="display: none;"></div>
        <?php echo $this->getChildChildHtml('additional'); ?>
        <div class="tool-tip" id="payment-tool-tip" style="display:none;">
            <div class="btn-close">
                <a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a>
            </div>
            <div class="tool-tip-content">
                <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
            </div>
        </div>
        <script type="text/javascript">
            var OSCPayment = new OnestepcheckoutPayment({
                containerSelector: "#onestepcheckout-payment-method",
                wrapContainerSelector: "#onestepcheckout-payment-method-wrapper",
                switchMethodInputsSelector: "input[name='payment[method]']",
                enterpriseRewardsSelector: 'use_reward_points',
                methodAdditionalContainerIdPrefix: "payment_form_",
                cvv: {
                    tooltipSelector: "#payment-tool-tip",
                    closeElSelector: "#payment-tool-tip-close",
                    triggerElsSelector: ".cvv-what-is-this"
                },
                savePaymentUrl: <?php echo Zend_Json::encode($this->getSavePaymentUrl()); ?>
            });
        </script>
        <?php echo $this->getChildHtml('extra'); ?>
    </div>
</div>
<script type="text/javascript">
$$('input[name="payment[method]"]').each(function(item,index){
    Element.observe(item,'change',function(){
        // for Discount purpose...
        OSCPayment.forcesavePayment();
        OSCShipment.switchToMethod(OSCShipment.currentMethod, true);
    });
});
</script>
