<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="col-xs-12 col-sm-6 col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->__('Default Billing Address') ?></h3>
            <div class="panel-actions">
                <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>" data-toggle="tooltip" title="<?php echo $this->__('Edit Address') ?>"><span class="fa fa-pencil"></span></a>
            </div>
        </div>
        <div class="panel-body">
            <address><?php echo $this->getPrimaryBillingAddressHtml() ?></address>
        </div>
    </div>
</div>

<div class="col-xs-12 col-sm-6 col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->__('Default Billing Address') ?></h3>
            <div class="panel-actions">
                <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>" data-toggle="tooltip" title="<?php echo $this->__('Edit Address') ?>"><span class="fa fa-pencil"></span></a>
            </div>
        </div>
        <div class="panel-body">
            <address><?php echo $this->getPrimaryShippingAddressHtml() ?></address>
        </div>
    </div>
</div>
