<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="col-xs-12 col-sm-6 col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3><?php echo $this->__('Contact Information') ?></h3>
            <div class="panel-actions">
                <a href="<?php echo $this->getUrl('customer/account/edit') ?>" data-toggle="tooltip" title="<?php echo $this->__('Edit') ?>"><span class="fa fa-pencil"></span></a>
                <a href="<?php echo $this->getChangePasswordUrl() ?>" data-toggle="tooltip" title="<?php echo $this->__('Change Password') ?>"><span class="fa fa-lock"></span></a>
            </div>
        </div>
        <div class="panel-body">
            <p>
                <?php echo $this->escapeHtml($this->getCustomer()->getName()) ?><br />
                <?php echo $this->escapeHtml($this->getCustomer()->getEmail()) ?>
            </p>
        </div>
    </div>
</div>

<?php if( $this->isNewsletterEnabled() ): ?>
    <div class="col-xs-12 col-sm-6 col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3><?php echo $this->__('Newsletters') ?></h3>
                <div class="panel-actions">
                    <a href="<?php echo $this->getUrl('newsletter/manage') ?>" data-toggle="tooltip" title="<?php echo $this->__('Edit') ?>"><span class="fa fa-pencil"></span></a>
                </div>
            </div>
            <div class="panel-body">
                <p>
                    <?php if( $this->getIsSubscribed() ): ?>
                        <?php echo $this->__("You are currently subscribed to 'General Subscription'.") ?>
                    <?php else: ?>
                        <?php echo $this->__('You are currently not subscribed to any newsletter.') ?>
                    <?php endif; ?>
                </p>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php echo $this->getChildHtml('customer.account.dashboard.info.extra')?>
