<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="cart">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="checkout-progress">
        <div class="checkout-block">
            <div class="checkout-status checkout-status-active">
                <div class="checkout-status-nunber">
                    <span><strong>01</strong></span>
                </div>

                <div class="checkout-status-label">
                    <span><strong><?php echo $this->__('Shopping Cart'); ?></strong></span>
                </div>
            </div>
        </div>
        <div class="checkout-block">
            <div class="checkout-status">
                <div class="checkout-status-nunber">
                    <span><strong>02</strong></span>
                </div>

                <div class="checkout-status-label">
                    <span><strong><?php echo $this->__('Proceed to Checkout'); ?></strong></span>
                </div>
            </div>
        </div>
        <div class="checkout-block">
            <div class="checkout-status">
                <div class="checkout-status-nunber">
                    <span><strong>03</strong></span>
                </div>

                <div class="checkout-status-label">
                    <span><strong><?php echo $this->__('Confirmation'); ?></strong></span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-8 col-lg-8">
            <?php echo $this->getChildHtml('form_before') ?>
            <form action="<?php echo $this->getFormActionUrl() ?>" method="post">
                <?php echo $this->getBlockHtml('formkey'); ?>
                <fieldset>
                    <table id="shopping-cart-table" class="data-table cart-table">
                        <col width="1" />
                        <col />
                        <col width="1" />
                    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                        <col width="1" />
                    <?php endif ?>
                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col width="1" />
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col width="1" />
                    <?php endif; ?>
                        <col width="1" />
                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col width="1" />
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                        <col width="1" />
                    <?php endif; ?>
                        <col width="1" />

                    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                        <thead>
                            <tr>
                                <th rowspan="<?php echo $mergedCells; ?>" class="image">&nbsp;</th>
                                <th rowspan="<?php echo $mergedCells; ?>" class="product"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                                <th rowspan="<?php echo $mergedCells; ?>"></th>
                                <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                                <th rowspan="<?php echo $mergedCells; ?>" class="wishlist"><span class="hidden"><?php echo $this->__('Wishlist') ?></span></th>
                                <?php endif ?>
                                <th class="pricing" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Price') ?></span></th>
                                <th rowspan="<?php echo $mergedCells; ?>" class="qty a-center"><?php echo $this->__('Qty') ?></th>
                                <th class="subtotal" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
                                <th rowspan="<?php echo $mergedCells; ?>" class="remove">&nbsp;</th>
                            </tr>
                            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                            <tr>
                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                                <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                                <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                            </tr>
                            <?php endif; ?>
                        </thead>
                        <tfoot>
                            <tr>
                                <td colspan="50" class="a-right">
                                    <?php if($this->getContinueShoppingUrl()): ?>
                                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Continue Shopping')) ?>" class="button btn-continue" onclick="setLocation('<?php echo Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl()) ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
                                    <?php endif; ?>
                                    <button type="submit" name="update_cart_action"  value="update_qty" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Update Shopping Cart')); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
                                    <button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Clear Shopping Cart')); ?>" class="button btn-empty" id="empty_cart_button"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
                                    <!--[if lt IE 8]>
                                    <input type="hidden" id="update_cart_action_container" />
                                    <script type="text/javascript">
                                    //<![CDATA[
                                        Event.observe(window, 'load', function()
                                        {
                                            // Internet Explorer (lt 8) does not support value attribute in button elements
                                            $emptyCartButton = $('empty_cart_button');
                                            $cartActionContainer = $('update_cart_action_container');
                                            if ($emptyCartButton && $cartActionContainer) {
                                                Event.observe($emptyCartButton, 'click', function()
                                                {
                                                    $emptyCartButton.setAttribute('name', 'update_cart_action_temp');
                                                    $cartActionContainer.setAttribute('name', 'update_cart_action');
                                                    $cartActionContainer.setValue('empty_cart');
                                                });
                                            }

                                        });
                                    //]]>
                                    </script>
                                    <![endif]-->
                                </td>
                            </tr>
                        </tfoot>
                        <tbody>
                        <?php foreach($this->getItems() as $_item): ?>
                            <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach ?>
                        </tbody>
                    </table>
                    <script type="text/javascript">decorateTable('shopping-cart-table')</script>
                </fieldset>
            </form> 
        </div>

        <aside class="col-xs-12 col-sm-5 col-md-4 col-lg-4">
            <div class="cart-collateral">
                <?php /* Extensions placeholder */ ?>
                <?php echo $this->getChildHtml('checkout.cart.extra') ?>
                <?php echo $this->getChildHtml('coupon') ?>
                <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>

                <div class="totals">
                    <h2 class="hidden"><?php echo $this->__('Total') ?></h2>
                    <?php echo $this->getChildHtml('totals'); ?>
                    <?php if(!$this->hasError()): ?>
                    <ul class="checkout-types">
                    <?php foreach ($this->getMethods('methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                        <li><?php echo $methodHtml; ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    </ul>
                    <?php endif; ?>
                </div>
            </div>
        </aside> 
    </div>

    <?php echo $this->getChildHtml('crosssell') ?>
</div>
