<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="row">
    <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8 col-lg-offset-2 col-lg-8">
        <div class="page-title a-center">
            <h1><?php echo $this->__('Checkout') ?></h1>
        </div>
        <script type="text/javascript" src="<?php echo $this->getJsUrl('varien/accordion.js') ?>"></script>
        <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/opcheckout.js') ?>"></script>

        <ol class="opc" id="checkoutSteps">
        <?php $i=0; foreach($this->getSteps() as $_stepId => $_stepInfo): ?>
        <?php if (!$this->getChild($_stepId) || !$this->getChild($_stepId)->isShow()): continue; endif; $i++ ?>
            <li id="opc-<?php echo $_stepId ?>" class="panel panel-default section<?php echo !empty($_stepInfo['allow'])?' allow':'' ?><?php echo !empty($_stepInfo['complete'])?' saved':'' ?>">
                <div class="panel-heading step-title">
                    <span class="number"><?php echo $i ?></span>
                    <h2><?php echo $_stepInfo['label'] ?></h2>
                    <a href="#" title="<?php echo $this->__('Edit') ?>" data-toggle="tooltip"><?php echo $this->__('Edit') ?></a>
                </div>
                <div id="checkout-step-<?php echo $_stepId ?>" class="panel-body step a-item" style="display:none;">
                    <?php echo $this->getChildHtml($_stepId) ?>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var accordion = new Accordion('checkoutSteps', '.step-title', true);
    <?php if($this->getActiveStep()): ?>
    accordion.openSection('opc-<?php echo $this->getActiveStep() ?>');
    <?php endif ?>
    var checkout = new Checkout(accordion,{
        progress: '<?php echo $this->getUrl('checkout/onepage/progress') ?>',
        review: '<?php echo $this->getUrl('checkout/onepage/review') ?>',
        saveMethod: '<?php echo $this->getUrl('checkout/onepage/saveMethod') ?>',
        failure: '<?php echo $this->getUrl('checkout/cart') ?>'}
    );
//]]>
</script>
