<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php if($this->getCurrencyCount()>1): ?>
<div class="currency">
	<div class="currency-switcher">
	    <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
	        <a href="<?php echo $this->getSwitchCurrencyUrl($_code) ?>" title="<?php echo $_name ?>" data-toggle="tooltip" data-placement="bottom" <?php if($_code==$this->getCurrentCurrencyCode()): ?> class="active"<?php endif; ?>><strong><span><span><?php echo $_code ?></span></span></strong>
	        </a>
	    <?php endforeach; ?>
	</div>
</div>
<?php endif; ?>
