<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php $this->setPreconfiguredValue(); ?>
<?php $_product = $this->getProduct(); ?>
<?php $_associatedProducts = $this->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<?php if ($this->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable() && $_hasAssociatedProducts): ?>
        <p class="availability in-stock"><span class="sr-only"><?php echo $this->__('Availability:') ?></span><span><?php echo $this->__('In stock') ?></span></p>
    <?php else: ?>
        <p class="availability out-of-stock"><span class="sr-only"><?php echo $this->__('Availability:') ?></span><span><?php echo $this->__('Out of stock') ?></span></p>
    <?php endif; ?>
<?php endif; ?>

<?php echo $this->getChildHtml('product_type_data_extra') ?>

<?php if ($_hasAssociatedProducts): ?>
    <div class="grouped-items">
        <ol>
        <?php foreach ($_associatedProducts as $_item): ?>
        <?php $_finalPriceInclTax = $this->helper('tax')->getPrice($_item, $_item->getFinalPrice(), true) ?>
            <li>
                <div class="product-details">
                    <span class="product-image" title="<?php echo $this->escapeHtml($_item->getName()) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_item, 'image')->resize(220) ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>">
                    </span>
                    <div class="product-wrap">
                        <h2 class="product-name">
                            <span><?php echo $this->escapeHtml($_item->getName()) ?></span>
                        </h2>
                        <?php if ($this->getCanShowProductPrice($_product)): ?>
                            <?php if ($this->getCanShowProductPrice($_item)): ?>
                                <?php echo $this->getPriceHtml($_item, true) ?>
                                <?php echo $this->getTierPriceHtml($_item) ?>
                            <?php endif; ?>
                        <?php endif; ?>

                        <?php if ($_item->getShortDescription()):?>
                            <div class="short-description">
                                <div class="std"><?php echo $_item->getShortDescription() ?></div>
                            </div>
                        <?php endif;?>
                    </div>
                </div>

                <div class="product-checkout">
                    <?php if ($_item->isSaleable()): ?>
                        <input type="text" name="super_group[<?php echo $_item->getId() ?>]" maxlength="12" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty hidden"/>
                        <a href="javascript:void(0)" class="button btn-success btn-lg" title="<?php echo $this->__('In Stock') ?>" data-toggle="tooltip" data-placement="top">
                            <span><span><?php echo $this->__('Add') ?></span></span>
                        </a>
                    <?php else: ?>
                        <a href="javascript:void(0)" class="button btn-lg out-of-stock" title="<?php echo $this->__('Out of stock') ?>" data-toggle="tooltip" data-placement="top">
                            <span><span><?php echo $this->__('Out of stock') ?></span></span>
                        </a>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
<?php endif; ?>
