<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="col-xs-12 col-sm-8 col-md-9 col-lg-9">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="dashboard">
        <?php echo $this->getChildHtml('top') ?>

        <h2><?php echo $this->__('Account Information') ?></h2>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('customer.account.dashboard.extra') ?>
        <div class="row">
            <?php echo $this->getChildHtml('address') ?>
            <?php echo $this->getChildHtml('info') ?>
            <?php echo $this->getChildHtml('info1') ?>
            <?php echo $this->getChildHtml('info2') ?>
        </div>
    </div>
</div>
