<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
<div class="cart-empty">
    <div class="text-center">
    	<br>
		<h1><?php echo $this->__('Shopping Cart is Empty') ?></h1>
	    <p>
	    	<?php echo $this->__('You have no items in your shopping cart.') ?>
	    	<?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', Mage::helper('core')->quoteEscape($this->getContinueShoppingUrl())) ?>
		</p>
		<br><br>
    </div>
    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
	<hr>
    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('category_no_results')->toHtml() ?>
</div>