<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
        <div class="wishlist-share">
            <div class="text-center">
                <h2><?php echo $this->__('Share Your Wishlist') ?></h2>
            </div>
            <form action="<?php echo $this->getSendUrl() ?>" id="form-validate" method="post">
                <?php echo $this->getBlockHtml('formkey')?>
                <div class="fieldset">
                    <h2 class="legend"><?php echo $this->__('Sharing Information') ?></h2>
                    <ul class="form-list row">
                        <li class="col-xs-6">
                            <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email addresses') ?></label>
                            <div class="input-box">
                                <textarea name="emails" cols="60" rows="5" id="email_address" class="validate-emails required-entry"><?php echo $this->getEnteredData('emails') ?></textarea>
                            </div>
                        </li>
                        <li class="col-xs-6">
                            <label for="message"><?php echo $this->__('Message') ?></label>
                            <div class="input-box">
                                <textarea id="message" name="message" cols="60" rows="5"><?php echo $this->getEnteredData('message') ?></textarea>
                            </div>
                        </li>
                        <?php if($this->helper('wishlist')->isRssAllow()): ?>
                        <li class="col-xs-12">
                            <div class="control">
                                <div class="input-box">
                                    <input type="checkbox" name="rss_url" id="rss_url" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Check this checkbox if you want to add a link to an rss feed to your wishlist.')) ?>" class="checkbox" />
                                </div>
                                <label for="rss_url"><?php echo $this->__('Check this checkbox if you want to add a link to an rss feed to your wishlist.') ?></label>
                            </div>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
                <div class="text-center">
                    <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Share Wishlist')) ?>" class="button"><span><span><?php echo $this->__('Share Wishlist') ?></span></span></button>
                </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
Validation.addAllThese([
    ['validate-emails', '<?php echo Mage::helper('core')->jsQuoteEscape($this->__('Please enter a valid email addresses, separated by commas. For example johndoe@domain.com, johnsmith@domain.com.')) ?>', function (v) {
    if(Validation.get('IsEmpty').test(v)) {
        return true;
    }

    var valid_regexp = /^[a-z0-9\._-]{1,30}@([a-z0-9_-]{1,30}\.){1,5}[a-z]{2,4}$/i;
    var emails = v.split(',');

    for (var i=0; i<emails.length; i++) {
        if(!valid_regexp.test(emails[i].strip())) {
            return false;
        }
    }

    return true;
    }]
]);
var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
