<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="row">
	<div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
		<div class="box-account-login">
			<div class="content text-center">
				<h2><?php echo Mage::helper('customer')->__('You are now logged out') ?></h2>
				<p><?php echo Mage::helper('customer')->__('You have logged out and will be redirected to our homepage in 5 seconds.') ?></p>
				<p class="loading-infinity"></p>
				<br>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
    setTimeout(function(){ location.href = '<?php echo $this->getUrl() ?>'},10000);
//]]>
</script>
