<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php
    $_categoryId = $this->getCategoryId();
    $_productCollection = Mage::getSingleton('catalog/category')->load($_categoryId)
            ->getProductCollection()
            ->addAttributeToSelect('*');
?>
<div class="carousel-section">
    <div class="carousel-title">
        <h2><span><?php echo $this->__( $this->getLabel() ); ?></span></h2>
    </div>
    <div class="carousel-content">
        <ul class="products-grid slick-default">
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item <?php if ($_product->isGrouped()): ?>item-grouped<?php endif; ?>">
                <div class="item-box">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(420); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <div class="item-wrap">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
                        <?php if($_product->getRatingSummary()):
                            echo $this->getReviewsSummaryHtml($_product, 'short');
                        endif; ?>

                        <?php if ($_product->isGrouped()): ?>
                            <?php $_associatedProducts = $_product->getTypeInstance(true)->getAssociatedProducts($_product); ?>
                            <?php $prices = [];
                                  $grouped_price = 0;
                                  $price_difference = 0;

                                foreach($_associatedProducts as $_item) {
                                    $id = $_item->getId();
                                    $product = Mage::getModel('catalog/product')->load($id);
                                    $prices[] = $product['price'];

                                    if ($product['special_price']) {
                                        $grouped_price += $product['special_price'];
                                        $price_difference += $product['price']-$product['special_price'];
                                        $old_price = $grouped_price + $price_difference;
                                    } else {
                                        $grouped_price += $product['price'];
                                        $old_price += $product['price'];
                                    }
                                }
                            ?>
                            <div class="price-box">
                                <span class="regular-price">
                                    <span class="price"><?php echo Mage::helper('core')->currency($grouped_price); ?></span>
                                </span>

                                <?php if ($old_price): ?>
                                    <?php if ($old_price != $grouped_price): ?>
                                        <span class="old-price">
                                            <span class="price"><?php echo Mage::helper('core')->currency($old_price); ?></span>
                                        </span>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        <?php else: ?>
                            <?php $_finalPrice = Mage::helper('core')->currency($_product->getFinalPrice(), true, false);
                                  $_basePrice  = Mage::helper('core')->currency($_product->getPrice(), true, false); ?>

                            <div class="price-box">
                                <div class="regular-price">
                                    <div class="price"><?php echo $_finalPrice ?></div>
                                </div>
                                
                                <?php if ($_finalPrice != $_basePrice): ?>
                                    <div class="old-price">
                                        <div class="price"><?php echo $_basePrice ?></div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>

                        <?php if ($_product->isGrouped()):
                            $_finalPrice  = $grouped_price; else:
                            $_finalPrice  = $_product->getFinalPrice();
                        endif; ?>
                        <?php $_paymentCashDiscount  = Mage::getStoreConfig('design/advanced_payment/payment_cash_discount'); ?>
                        <?php $_paymentPlots         = Mage::getStoreConfig('design/advanced_payment/payment_plots'); ?>
                        <?php $_paymentFreePlots     = Mage::getStoreConfig('design/advanced_payment/payment_free_plots'); ?>
                        <?php $_paymentPlotsShow     = Mage::getStoreConfig('design/advanced_payment/payment_plots_show'); ?>
                        <?php if ($_paymentFreePlots):
                            $_paymentPlotslabel = $this->__('no tax'); else:
                            $_paymentPlotslabel = $this->__('on credit card');
                        endif; ?>
                        <ul class="price-new">
                            <?php if ($_paymentPlots): ?>
                                <li class="price-plots-block">
                                    <?php echo '<li>' . $_paymentPlotsShow . 'x ' . $this->__('of') . ' <strong>' . $this->helper('core')->currency($_finalPrice / $_paymentPlotsShow, true, false) . '</strong> ' . $_paymentPlotslabel . '</li>'; ?>
                                </li>
                            <?php endif; ?>
                            <?php
                                if($_paymentCashDiscount):
                                $_calcDiscount = ($_paymentCashDiscount / 100) * $_finalPrice;
                                $_calcFinal    = $this->helper('core')->currency($_finalPrice - $_calcDiscount, true, false);
                            ?>
                                <li class="price-barcode-block">
                                    <strong class="barcode-price-label"><?php echo $_paymentCashDiscount . '% ' . $this->__('OFF cash payment'); ?></strong>
                                    <span class="special-price barcode-price"><span class="price"><?php echo $_calcFinal; ?></span></span>
                                </li>
                            <?php endif; ?>
                        </ul>

                        <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <ul class="add-to-links">
                                <?php echo Mage::helper('netgo_gwishlist')->getUrl($_product); ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
