<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php
    $_categoryId = $this->getCategoryId();
    $_productCollection = Mage::getSingleton('catalog/category')->load($_categoryId)
            ->getProductCollection()
            ->addAttributeToSelect('*');
?>
<div class="carousel-section">
    <div class="carousel-title">
        <h2><span><?php echo $this->__( $this->getLabel() ); ?></span></h2>
    </div>
    <div class="carousel-content">
        <ul class="products-grid slick-default">
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item <?php if ($_product->isGrouped()): ?>item-grouped<?php endif; ?>">
                <div class="item-box">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(420); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                    <div class="item-wrap">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
                        <?php if($_product->getRatingSummary()):
                            echo $this->getReviewsSummaryHtml($_product, 'short');
                        endif; ?>
                        <?php //echo $this->getPriceHtml($_product, true) ?>

                        <?php if ($_product->isGrouped()):
                            $_associatedProducts = $_product->getTypeInstance(true)->getAssociatedProducts($_product);
                            $prices = [];
                            $grouped_price = 0;
                            $price_difference = 0;

                            foreach($_associatedProducts as $_item) {
                                $id = $_item->getId();
                                $product = Mage::getModel('catalog/product')->load($id);
                                $prices[] = $product['price'];

                                if ($product['special_price']) {
                                    $grouped_price += $product['special_price'];
                                    $price_difference += $product['price']-$product['special_price'];
                                    $old_price = $grouped_price + $price_difference;
                                } else {
                                    $grouped_price += $product['price'];
                                    $old_price += $product['price'];
                                }
                            }

                            arsort($prices); // get highest price
                            $price_array = array_keys($prices);
                            $highest_price = $prices[$price_array[0]]; 
                        ?>

                            <?php //echo $this->__('Highest price:') ?>
                            <?php //echo Mage::helper('core')->currency($highest_price) ?>

                            <div class="price-box">
                                <span class="regular-price">
                                    <span class="price"><?php echo Mage::helper('core')->currency($grouped_price); ?></span>
                                </span>
                                <?php if ($old_price): ?>
                                    <span class="old-price">
                                        <span class="price"><?php echo Mage::helper('core')->currency($old_price); ?></span>
                                    </span>
                                <?php endif; ?>
                            </div>

                            <?php //if ($price_difference): ?>
                                <?php //echo $this->__('Total save with all these products:') ?>
                                <?php //echo Mage::helper('core')->currency($price_difference) ?>
                            <?php //endif; ?>

                        <?php else: ?>
                            <?php $_finalPrice = Mage::helper('core')->currency($_product->getFinalPrice(), true, false);
                                  $_basePrice  = Mage::helper('core')->currency($_product->getPrice(), true, false); ?>

                            <div class="price-box">
                                <div class="regular-price">
                                    <div class="price"><?php echo $_finalPrice ?></div>
                                </div>
                                
                                <?php if ($_finalPrice != $_basePrice): ?>
                                    <div class="old-price">
                                        <div class="price"><?php echo $_basePrice ?></div>
                                    </div>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>

                        <?php if ($_product->isGrouped()):
                            $_finalPrice  = $grouped_price; else:
                            $_finalPrice  = $_product->getFinalPrice();
                        endif; ?>

                        <ul class="price-new">
                            <?php
                                $_plots = $_product->getData('price_plots');
                                $_plots_tax = $_product->getData('plots_tax');
                                if($_plots != ""):
                            ?>
                                <li class="price-plots-block">
                                    <?php echo '<strong> '.$_plots .'x '.$this->__('of').' '.$this->helper('core')->currency(($_finalPrice * $_plots_tax) + $_finalPrice / $_plots, true, false).' '.$this->__('interest-free').'</strong>' ?>
                                </li>
                            <?php endif; ?>
                            <?php
                                $_barcode     = $_product->getData('discount_barcode');
                                $_calcBarcode = ($_barcode / 100) * $_finalPrice;
                                $_calcFinal   = $this->helper('core')->currency($_finalPrice - $_calcBarcode, true, false);
                                if($_barcode != ""):
                            ?>
                                <li class="price-barcode-block">
                                    <strong class="barcode-price-label"><?php echo $_barcode.'% '.' off '.$this->__('via barcode');  ?></strong>
                                    <span class="special-price barcode-price"><span class="price"><?php echo $_calcFinal; ?></span></span>
                                </li>
                            <?php endif; ?>
                        </ul>

                        <div class="actions">
                            <?php if($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <ul class="add-to-links">
                                <?php echo Mage::helper('netgo_gwishlist')->getUrl($_product); ?>
                                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                    <li><a href="<?php echo $_compareUrl ?>" class="link-compare" data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
