<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
    <p class="amount">
        <?php if($this->getLastPageNum()>1): ?>
            <?php echo $this->__('Items %s to %s of %s total', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
        <?php else: ?>
            <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
        <?php endif; ?>
    </p>

    <?php if( $this->isEnabledViewSwitcher() ): ?>
    <p class="view-mode">
        <?php $_modes = $this->getModes(); ?>
        <?php if($_modes && count($_modes)>1): ?>
        <label><?php echo $this->__('View as') ?>:</label>
        <?php foreach ($this->getModes() as $_code=>$_label): ?>
            <?php if($this->isModeActive($_code)): ?>
                <strong title="<?php echo $_label ?>" data-toggle="tooltip" data-placement="top" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
            <?php else: ?>
                <a href="<?php echo $this->getModeUrl($_code) ?>" data-toggle="tooltip" data-placement="top" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
            <?php endif; ?>
        <?php endforeach; ?>
        <?php endif; ?>
    </p>
    <?php endif; ?>

    <?php if( $this->isExpanded() ): ?>
    <div class="sorter">
        <div class="limiter">
            <label><?php echo $this->__('Show') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $this->getLimitUrl($_key) ?>"<?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select>
        </div>
        
        <div class="sort-by">
            <label><?php echo $this->__('Sort By') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach; ?>
            </select>
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" data-toggle="tooltip" data-placement="top" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?>" class="direction-asc"><?php echo Mage::helper('core')->quoteEscape($this->__('Set Ascending Direction')) ?></a>
            <?php else: ?>
                <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" data-toggle="tooltip" data-placement="top" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?>" class="direction-desc"><?php echo Mage::helper('core')->quoteEscape($this->__('Set Descending Direction')) ?></a>
            <?php endif; ?>
        </div>

        <button class="button btn-filters"><span><span><?php echo $this->__('Filter') ?></span></span></button>
    </div>
    <?php endif; ?>

    <?php echo $this->getPagerHtml() ?>
</div>
<?php endif ?>
