<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    <ul class="products-grid" id="upsell-product-list">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <li class="item <?php if ($_link->isGrouped()): ?>item-grouped<?php endif; ?>">
                <div class="item-box">
                    <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(420) ?>" alt="<?php echo $this->escapeHtml($_link->getName()) ?>" /></a>
                    <h3 class="product-name"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_link->getName()) ?>"><?php echo $this->escapeHtml($_link->getName()) ?></a></h3>
                    <?php echo $this->getReviewsSummaryHtml($_link) ?>

                    <?php if ($_link->isGrouped()): ?>
                        <?php $_associatedProducts = $_link->getTypeInstance(true)->getAssociatedProducts($_link); ?>
                        <?php $prices = [];
                              $grouped_price = 0;
                              $price_difference = 0;

                            foreach($_associatedProducts as $_link) {
                                $id = $_link->getId();
                                $product = Mage::getModel('catalog/product')->load($id);
                                $prices[] = $product['price'];

                                if ($product['special_price']) {
                                    $grouped_price += $product['special_price'];
                                    $price_difference += $product['price']-$product['special_price'];
                                    $old_price = $grouped_price + $price_difference;
                                } else {
                                    $grouped_price += $product['price'];
                                    $old_price += $product['price'];
                                }
                            }
                        ?>
                        <div class="price-box">
                            <span class="regular-price">
                                <span class="price"><?php echo Mage::helper('core')->currency($grouped_price); ?></span>
                            </span>

                            <?php if ($old_price): ?>
                                <?php if ($old_price != $grouped_price): ?>
                                    <span class="old-price">
                                        <span class="price"><?php echo Mage::helper('core')->currency($old_price); ?></span>
                                    </span>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    <?php else: ?>
                        <?php echo $this->getPriceHtml($_link, true); ?>
                    <?php endif; ?>

                    <?php if ($_link->isGrouped()):
                        $_finalPrice  = $grouped_price; else:
                        $_finalPrice  = $_link->getFinalPrice();
                    endif; ?>
                    <?php $_paymentCashDiscount  = Mage::getStoreConfig('general/advanced_payment/payment_cash_discount'); ?>
                    <?php $_paymentPlots         = Mage::getStoreConfig('general/advanced_payment/payment_plots'); ?>
                    <?php $_paymentFreePlots     = Mage::getStoreConfig('general/advanced_payment/payment_free_plots'); ?>
                    <?php $_paymentPlotsShow     = Mage::getStoreConfig('general/advanced_payment/payment_plots_show'); ?>
                    <?php if ($_paymentFreePlots):
                        $_paymentPlotslabel = $this->__('no tax'); else:
                        $_paymentPlotslabel = $this->__('on credit card');
                    endif; ?>
                    <ul class="price-new">
                        <?php if ($_paymentPlots): ?>
                            <li class="price-plots-block">
                                <?php echo '<li>' . $_paymentPlotsShow . 'x ' . $this->__('of') . ' <strong>' . $this->helper('core')->currency($_finalPrice / $_paymentPlotsShow, true, false) . '</strong> ' . $_paymentPlotslabel . '</li>'; ?>
                            </li>
                        <?php endif; ?>
                        <?php
                            if($_paymentCashDiscount):
                            $_calcDiscount = ($_paymentCashDiscount / 100) * $_finalPrice;
                            $_calcFinal    = $this->helper('core')->currency($_finalPrice - $_calcDiscount, true, false);
                        ?>
                            <li class="price-barcode-block">
                                <strong class="barcode-price-label"><?php echo $_paymentCashDiscount . '% ' . $this->__('OFF cash payment'); ?></strong>
                                <span class="special-price barcode-price"><span class="price"><?php echo $_calcFinal; ?></span></span>
                            </li>
                        <?php endif; ?>
                    </ul>

                    <div class="actions">
                        <?php if($_link->isSaleable()): ?>
                            <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <ul class="add-to-links">
                            <?php echo Mage::helper('netgo_gwishlist')->getUrl($_link); ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_link)): ?>
                                <li><a href="<?php echo $_compareUrl ?>" class="link-compare" data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </li>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endfor; ?>
    </ul>
    <script type="text/javascript">decorateTable('upsell-product-list')</script>
</div>
<?php endif ?>
