<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="row">
    <?php echo $this->getMessagesBlock()->toHtml() ?>    
    <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
        <div class="box-account-login">
            <div class="content">
                <div class="text-center">
                    <h2><?php echo $this->__('Change Account Password') ?></h2>
                </div>
                <form action="<?php echo $action ?>" method="post" id="form-validate">
                    <div class="fieldset">
                        <h2 class="legend"><?php echo $this->__('Change Account Password') ?></h2>
                        <ul class="form-list">
                            <li>
                                <label for="current_password" class="required"><em>*</em><?php echo $this->__('Current Password') ?></label>
                                <div class="input-box">
                                    <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Current Password')) ?>" class="input-text required-entry" name="current_password" id="current_password" />
                                </div>
                            </li>
                            <li class="fields">
                                <div class="field">
                                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password') ?></label>
                                    <div class="input-box">
                                        <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('New Password')) ?>" class="input-text required-entry validate-password" name="password" id="password" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password') ?></label>
                                    <div class="input-box">
                                        <input type="password" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm New Password')) ?>" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="buttons-set">
                        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
                        <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save Password')) ?>" class="button"><span><span><?php echo $this->__('Save Password') ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate');
//]]>
</script>
