<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="row">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
        <div class="box-account-login">
            <div class="content">
                <div class="text-center">
                    <h2><?php echo $this->__('Send confirmation link') ?></h2>
                </div>
                <form action="" method="post" id="form-validate">
                    <div class="fieldset">
                        <h2 class="legend"><?php echo $this->__('Retrieve your confirmation link here') ?></h2>
                        <p><?php echo $this->__('Please enter your email below and we\'ll send you confirmation link for it.') ?></p>
                        <ul class="form-list">
                            <li>
                                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="text" name="email" id="email_address" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmail()) ?>" />
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="buttons-set">
                        <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
                        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
