<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="col-xs-12 col-sm-8 col-md-9 col-lg-9">
    <?php echo $this->getMessagesBlock()->toHtml() ?>

    <div class="page-title">
        <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
    </div>
    
    <?php echo $this->getChildHtml('form_before')?>
    <form action="<?php echo $this->getAction() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <?php echo $this->getBlockHtml('formkey')?>
            <h2 class="legend"><?php echo $this->__('Subscription Type') ?></h2>
            <ul class="form-list">
                <li class="control"><input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo Mage::helper('core')->quoteEscape($this->__('General Subscription')) ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" /><label for="subscription"><?php echo $this->__('General Subscription') ?></label></li>
                <?php /* Extensions placeholder */ ?>
                <?php echo $this->getChildHtml('customer.form.newsletter.extra')?>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Save')) ?>" class="button"><span><span><?php echo $this->__('Save') ?></span></span></button>
        </div>
    </form>
</div>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('customer.form.newsletter.extra2')?>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
