<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php if ($this->canShow()): ?>
<div id="onestepcheckout-review-comments">
   <?php echo $this->getChildHtml('simple');?>
</div>
<script type="text/javascript">
    var OSCReviewComments = new OnestepcheckoutReviewComments({
        containerSelector: "#onestepcheckout-review-comments",
        newRowCount: 5,
        saveValuesUrl: <?php echo Zend_Json::encode($this->getSaveFormValuesUrl());?>
    });
</script>
<?php endif;?>