<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div id="onestepcheckout-review-coupon">
<?php if ($this->canShow()): ?>
    <div class="coupon-code-form discount">
        <div class="simple-collapse">
            <h5 class="collapse-title"><?php echo $this->__('Discount Codes') ?></h5>
            <div class="collapse-content">
                <p><?php echo $this->__('Enter your coupon code if you have one.') ?></p>
                <label for="coupon_code"><?php echo $this->__('Cupom') ?></label>
                <div class="input-box">
                    <div class="input-group">
                        <input class="input-text<?php if ($this->getConfig()->isApplyCouponButton()) : ?> with-buttons<?php endif; ?>" id="coupon_code" name="coupon_code" value="<?php echo $this->getCouponCode(); ?>" />
                        <?php if ($this->getConfig()->isApplyCouponButton()) : ?>
                        <div class="input-group-btn">
                            <button type="submit" class="button" id="onestepcheckout-coupon-code-apply-btn" onclick="return false;"<?php if ($this->getCouponCode()) : ?> style="display:none;"<?php endif; ?>>
                                <span><span><?php echo $this->__('Apply'); ?></span></span>
                            </button>
                            <button type="submit" class="button" id="onestepcheckout-coupon-code-cancel-btn" onclick="return false;"<?php if (!$this->getCouponCode()) : ?> style="display:none;"<?php endif; ?>>
                                <span><span><?php echo $this->__('Cancel Coupon'); ?></span></span>
                            </button>
                        </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div class="coupon-message-container" style="overflow:hidden;height:0px;"></div>
        </div>
    </div>
    <script type="text/javascript">
        var OSCReviewCoupon = new OnestepcheckoutReviewCoupon({
            isCouponApplied: <?php echo ($this->getCouponCode()) ? 'true' : 'false'; ?>,
            isApplyCouponButton: <?php echo ($this->getConfig()->isApplyCouponButton()) ? 'true' : 'false'; ?>,
            applyCouponButtonSelector: '#onestepcheckout-coupon-code-apply-btn',
            cancelCouponButtonSelector: '#onestepcheckout-coupon-code-cancel-btn',
            msgContainerSelector: '.coupon-message-container',
            applyCouponUrl: '<?php echo $this->getApplyCouponAjaxUrl(); ?>',
            cancelCouponUrl: '<?php echo $this->getCancelCouponAjaxUrl(); ?>',
            couponCodeInput: 'coupon_code',
            successMessageBoxCssClass: 'onestepcheckout-success-msg',
            errorMessageBoxCssClass: 'onestepcheckout-error-msg',
            jsErrorMsg: <?php echo Zend_Json::encode($this->__("Oops something's wrong")); ?>,
            jsSuccessMsg: <?php echo Zend_Json::encode($this->__("Ok")); ?>
        });

        jQuery.noConflict();
          (function( $ ) {
            $(function() {

                $('.discount .collapse-title').click(function() {
                    $(this).parent().find(".collapse-content").toggleClass("active");
                    $(this).toggleClass("active");
                });

            });
        })(jQuery);
    </script>
<?php endif; ?>
</div>