<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php if ($this->canShow()): ?>
<div id="onestepcheckout-review-terms">
    <ol>
    <?php foreach($this->getAgreements() as $_a): ?>
        <li class="control">
            <input type="checkbox" name="inovarti_osc_agreement[<?php echo $_a->getId();?>]"
                   id="onestepcheckout-review-terms-agreement-<?php echo $_a->getId();?>"
                   class="checkbox osc-agreement-checkbox-<?php echo $_a->getId();?>" value="1" class="checkbox" />
            <?php $label = '<a href="javascript:void(0)" title="' . $this->htmlEscape($_a->getCheckboxText()) . '">' .
                $this->htmlEscape($_a->getCheckboxText()) . '</a>';
            ?>
            <label for="onestepcheckout-review-terms-agreement-<?php echo $_a->getId();?>"><?php echo $this->__('I accept the %s', $label) ?></label>
            <div class="onestepcheckout-review-terms-description-container hidden">
                <?php $terms_page = Mage::getModel('cms/page')->load('termos-de-uso', 'identifier')->getContent(); ?>
                <?php echo $terms_page; ?>
            </div>
        </li>
        <script type="text/javascript">
            Validation.add(
                'osc-agreement-checkbox-<?php echo $_a->getId();?>',
                <?php echo Zend_Json::encode($this->__('You must accept the "%s"', $this->htmlEscape($_a->getCheckboxText()))); ?>,
                function(v) {
                    return !Validation.get('IsEmpty').test(v);
                }
            );
        </script>
    <?php endforeach;?>
    </ol>
    <div id="onestepcheckout-review-terms-popup" class="onestepcheckout-popup" style="display:none">
        <div id="onestepcheckout-review-terms-popup-content" class="onestepcheckout-popup-content"></div>
        <div id="onestepcheckout-review-terms-popup-accept" class="onestepcheckout-popup-accept">
            <button type="button" class="btn btn-primary"><?php echo $this->__('I accept'); ?></button>
            <a href="javascript:void(0)" class="btn btn-default"><?php echo $this->__('Close'); ?></a>
        </div>
    </div>
    <div id="onestepcheckout-review-terms-overlay" class="onestepcheckout-popup-overlay" style="display:none"></div>
</div>
<script type="text/javascript">
    var OSCReviewTerms = new OnestepcheckoutReviewTerms({
        containerSelector: "#onestepcheckout-review-terms",
        itemsSelector: "#onestepcheckout-review-terms ol li",
        linkFromItemSelector: "label a",
        checkboxFromItemSelector: "input[type=checkbox]",
        descriptionContainerFromItemSelector: ".onestepcheckout-review-terms-description-container",
        popup: {
            overlaySelector: "#onestepcheckout-review-terms-overlay",
            containerSelector: "#onestepcheckout-review-terms-popup",
            contentContainerSelector: "#onestepcheckout-review-terms-popup-content",
            acceptContainerSelector: "#onestepcheckout-review-terms-popup-accept",
            buttons: {
                accept:{
                    selector: "#onestepcheckout-review-terms-popup-accept button",
                    enabled: true
                },
                close:{
                    selector: "#onestepcheckout-review-terms-popup-accept a",
                    enabled: true
                }
            }
        }
    });
</script>
<?php endif;?>