<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="row">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
        <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
            <div class="box-account-login">
                <div class="content">
                    <div class="text-center">
                        <h2><?php echo $this->__('Forgot Your Password?') ?></h2>
                    </div>
                    <div class="fieldset">
                        <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
                        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
                        <ul class="form-list">
                            <li>
                                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                <div class="input-box">
                                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
                                </div>
                            </li>
                            <?php echo $this->getChildHtml('form.additional.info'); ?>
                        </ul>
                    </div>
                    <div class="buttons-set">
                        <p class="back-link"><a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><small>&laquo; </small><?php echo $this->__('Back to Login') ?></a></p>
                        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Submit')) ?>" class="button"><span><span><?php echo $this->__('Submit') ?></span></span></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>    
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
