<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="row">
    <?php echo $this->getMessagesBlock()->toHtml(); ?>
    <div class="col-xs-12 col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6">
        <div class="box-account-login">
            <div class="content">
                <div class="text-center">
                    <h2><?php echo $this->__('Reset a Password'); ?></h2>
                </div>
                <form action="<?php echo $this->getUrl('*/*/resetpasswordpost'); ?>" method="post" id="form-validate">
                    <div class="fieldset" style="margin-top: 20px;">
                        <ul class="form-list">
                            <li class="fields">
                                <div class="field">
                                    <label for="password" class="required"><em>*</em><?php echo $this->__('New Password'); ?></label>
                                    <div class="input-box">
                                        <input type="password" class="input-text required-entry validate-password" name="password" id="password" />
                                    </div>
                                </div>
                                <div class="field">
                                    <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm New Password'); ?></label>
                                    <div class="input-box">
                                        <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation" />
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="buttons-set">
                        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Reset a Password')); ?>" class="button"><span><span><?php echo $this->__('Reset a Password'); ?></span></span></button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
/*<![CDATA[*/
    var dataForm = new VarienForm('form-validate', true);
/*]]>*/
</script>
