<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div id="onestepcheckout-review-comments-simple">
	<div class="simple-collapse">
		<h5 class="collapse-title"><?php echo $this->__('Comments') ?></h5>
	    <div class="field-row collapse-content">
	        <div class="input-box">
	            <textarea name="comments" id="comments" rows="2"><?php echo $this->getComments(); ?></textarea>
	        </div>
	    </div>
    </div>
</div>
