<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php $_baseUrl = Mage::getBaseUrl(); ?>
<div class="store-features">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<hr>
			</div>
			<?php $_shippingFree = Mage::getStoreConfig('design/advanced_shipping/free_shipping'); ?>
			<?php if ($_shippingFree): ?>
				<div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
					<div class="feature-box">
						<div class="feature-icon">
							<span class="feature-icon-shipping"></span>
						</div>
						<div class="feature-content">
							<strong><?php echo $this->__('Free Shipping'); ?></strong>
							<span><?php echo $this->__('Shop') . ' +' . Mage::helper('core')->currency($_shippingFree); ?></span>
						</div>
					</div>
				</div>
			<?php endif; ?>
			
			<?php $_paymentCash = Mage::getStoreConfig('design/advanced_payment/payment_cash_discount'); ?>
			<?php if ($_paymentCash): ?>
				<div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
					<div class="feature-box">
						<div class="feature-icon">
							<span class="feature-icon-barcode"></span>
						</div>
						<div class="feature-content">
							<strong><?php echo $_paymentCash . $this->__('% off') ?></strong>
							<span><?php echo $this->__('on cash payment'); ?></span>
						</div>
					</div>
				</div>
			<?php endif; ?>

			<?php $_paymentPlots = Mage::getStoreConfig('design/advanced_payment/payment_plots'); ?>
			<?php $_paymentFreePlots = Mage::getStoreConfig('design/advanced_payment/payment_free_plots'); ?>
			<?php $_paymentShow = Mage::getStoreConfig('design/advanced_payment/payment_plots_show'); ?>
			<?php  if ($_paymentFreePlots) {
				$_paymentTax = $this->__('no tax'); } else {
				$_paymentTax = $this->__('on credit card'); } 
			?>
			<?php if ($_paymentPlots): ?>
				<div class="col-xs-12 col-sm-4 col-md-3 col-lg-3">
					<div class="feature-box">
						<div class="feature-icon">
							<span class="feature-icon-credit-card"></span>
						</div>
						<div class="feature-content">
							<strong>Parcele em até</strong>
							<span><?php echo $_paymentShow . 'x ' . $_paymentTax; ?></span>
						</div>
					</div>
				</div>
			<?php endif; ?>
				
			<div class="hidden-xs hidden-sm col-md-3 col-lg-3">
				<div class="feature-box">
					<div class="feature-icon">
						<span class="feature-icon-warranty"></span>
					</div>
					<div class="feature-content">
						<strong>1 ano de garantia</strong>
						<span>p/todo nosso Catálogo</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<footer class="default">
	<div class="footer-top">
		<div class="container">
			<div class="row middle-xs">
				<div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
					<div class="footer-contact">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_contact')->toHtml() ?>
					</div>
				</div>

				<div class="col-xs-12 col-sm-5 col-md-5 col-lg-5">
					<div class="footer-social">
						<ul>
							<?php $_socialFacebook  = Mage::getStoreConfig('design/social/facebook'); ?>
							<?php $_socialInstagram = Mage::getStoreConfig('design/social/instagram'); ?>
							<?php $_socialTwitter   = Mage::getStoreConfig('design/social/twitter'); ?>
							<?php $_socialPinterest = Mage::getStoreConfig('design/social/pinterest'); ?>
							<?php if ($_socialFacebook): ?>
								<li class="facebook"><a href="https://facebook.com/<?php echo $_socialFacebook ?>" title="Facebook" data-toggle="tooltip" target="_blank">Facebook</a></li>
							<?php endif ?>
							<?php if ($_socialInstagram): ?>
								<li class="instagram"><a href="https://instagram.com/<?php echo $_socialInstagram ?>" title="Instagram" data-toggle="tooltip" target="_blank">Instagram</a></li>
							<?php endif ?>
							<?php if ($_socialTwitter): ?>
								<li class="twitter"><a href="https://twitter.com/<?php echo $_socialTwitter ?>" title="Twitter" data-toggle="tooltip" target="_blank">Twitter</a></li>
							<?php endif ?>
							<?php if ($_socialPinterest): ?>
								<li class="pinterest"><a href="https://twitter.com/<?php echo $_socialPinterest ?>" title="Pinterest" data-toggle="tooltip" target="_blank">Pinterest</a></li>
							<?php endif ?>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="footer-middle">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
					<div class="footer-links">
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml() ?>
					</div>
				</div>

				<div class="col-xs-12 hidden-sm col-md-4 col-lg-4">
					<div class="footer-newsletter">
						<h5><?php echo $this->__('Newsletter') ?></h5>
						<?php echo $this->getChildHtml('newsletter'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="footer-bottom">
		<div class="container">
			<div class="row middle-xs">
				<div class="col-xs-12 col-sm-6 col-md-7 col-lg-7">
					<div class="footer-payment">
						<ul>
							<?php $_paymentVisa       = Mage::getStoreConfig('design/payment_flags/flag_visa'); ?>
							<?php $_paymentMastercard = Mage::getStoreConfig('design/payment_flags/flag_mastercard'); ?>
							<?php $_paymentElo        = Mage::getStoreConfig('design/payment_flags/flag_elo'); ?>
							<?php $_paymentAmerican   = Mage::getStoreConfig('design/payment_flags/flag_american'); ?>
							<?php $_paymentDiners     = Mage::getStoreConfig('design/payment_flags/flag_diners'); ?>
							<?php $_paymentHipercard  = Mage::getStoreConfig('design/payment_flags/flag_hipercard'); ?>
							<?php $_paymentJcb        = Mage::getStoreConfig('design/payment_flags/flag_jcb'); ?>
							<?php $_paymentBoleto     = Mage::getStoreConfig('design/payment_flags/flag_boleto'); ?>
							<?php if ($_paymentVisa): ?>
								<li class="visa"><span title="Visa" data-toggle="tooltip">Visa</span></li>
							<?php endif ?>
							<?php if ($_paymentMastercard): ?>
								<li class="mastercard"><span title="Mastercard" data-toggle="tooltip">Mastercard</span></li>
							<?php endif ?>
							<?php if ($_paymentElo): ?>
								<li class="elo"><span title="Elo" data-toggle="tooltip">Elo</span></li>
							<?php endif ?>
							<?php if ($_paymentAmerican): ?>
								<li class="american-express"><span title="American Express" data-toggle="tooltip">American Express</span></li>
							<?php endif ?>
							<?php if ($_paymentDiners): ?>
								<li class="diners hidden-xs hidden-sm"><span title="Diners" data-toggle="tooltip">Diners</span></li>
							<?php endif ?>
							<?php if ($_paymentHipercard): ?>
								<li class="hipercard"><span title="Hipercard" data-toggle="tooltip">Hipercard</span></li>
							<?php endif ?>
							<?php if ($_paymentJcb): ?>
								<li class="jcb hidden-xs hidden-sm"><span title="JCB" data-toggle="tooltip">JCB</span></li>
							<?php endif ?>
							<?php if ($_paymentBoleto): ?>
								<li class="boleto"><span title="Boleto" data-toggle="tooltip">Boleto</span></li>
							<?php endif ?>
						</ul>
					</div>
				</div>

				<div class="col-xs-12 col-sm-6 col-md-5 col-lg-5">
					<div class="footer-security">
						<ul>
							<?php $_securityGoogle   = Mage::getStoreConfig('design/security/google'); ?>
							<?php $_securityComodo   = Mage::getStoreConfig('design/security/comodo'); ?>
							<?php $_securityGeotrust = Mage::getStoreConfig('design/security/geotrust'); ?>
							<?php $_securityVerisign = Mage::getStoreConfig('design/security/verisign'); ?>
							<?php if ($_securityGoogle): ?>
								<li title="Google Safe" data-toggle="tooltip"><a href="https://transparencyreport.google.com/safe-browsing/search?url=<?php echo $_baseUrl ?>" target="_blank"><img alt="Google Safe" src="<?php echo $this->getSkinUrl('images/seal-google.png'); ?>" /> </a></li>
							<?php endif; ?>
							<?php if ($_securityComodo): ?>
								<li title="Comodo" data-toggle="tooltip"><a href="javascript:void(0)"> <img alt="Comodo" src="<?php echo $this->getSkinUrl('images/seal-comodo.png'); ?>" /> </a></li>
							<?php endif; ?>
							<?php if ($_securityGeotrust): ?>
								<li title="GeoTrust" data-toggle="tooltip"><a href="javascript:void(0)"> <img alt="GeoTrust" src="<?php echo $this->getSkinUrl('images/seal-geotrust.png'); ?>" /> </a></li>
							<?php endif; ?>
							<?php if ($_securityVerisign): ?>
								<li title="Verisign" data-toggle="tooltip"><a href="javascript:void(0)"> <img alt="Verisign" src="<?php echo $this->getSkinUrl('images/seal-verisign.png'); ?>" /> </a></li>
							<?php endif; ?>
						</ul>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12">
					<p class="copyright"><?php echo $this->getCopyright() ?></p>
				</div>
			</div>
		</div>
	</div>
</footer>
