<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php /** @var $this Mage_Sales_Block_Order_Info */ ?>
<div class="col-xs-12 col-sm-8 col-md-9 col-lg-9">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <?php 
        $_order         = $this->getOrder();
        $order_id       = $_order->getRealOrderId();
        $order_status   = $_order->getStatusLabel();
        $order_date     = $this->formatDate($_order->getCreatedAtStoreDate());
        $order_shipping = $_order->getShippingMethod();
        $order_shippingTitle  = $_order->getShippingDescription();
        $order_track    = $_order->getTrackingNumbers();
        $order_payment  = $_order->getPayment()->getMethodInstance()->getTitle();
        $order_paymentCode = $_order->getPayment()->getMethodInstance()->getCode();
        $order_paymentInfo = $_order->getPayment()->getMethodInstance()->getDescription();
        $order_total    = $_order->formatPrice($_order->getGrandTotal());
    ?>

    <div class="order-details-timeline">
        <div class="timeline-list">
            <div class="timeline-item timeline-success">
                <div class="timeline-number">01</div>
                <div class="timeline-info">
                    <strong>Pedido Realizado</strong> <br>
                    <span><?php echo 'Em ', $order_date ?></span>
                </div>
            </div>

            <?php if ($order_status == "Pedido Realizado" || $order_status == "Pagamento Realizado" || $order_status == "Concluído"): ?>
            <div class="timeline-item timeline-<?php if ($order_status == "Pagamento Realizado" || $order_status == "Concluído") {
                    echo "success"; } elseif ($order_status == "Pedido Realizado") { echo "info"; } else { echo "default"; } ?>">
                <div class="timeline-number">02</div>
                <div class="timeline-info">
                    <strong>
                        <?php if ($order_status == "Pagamento Realizado" || $order_status == "Concluído") {
                            echo "Pagamento Realizado";
                        } else {
                            echo "Aguardando Pagamento";
                        } ?>
                    </strong> <br>
                    <span>
                        <?php if ($order_status == "Pagamento Realizado" || $order_status == "Concluído") {
                            echo "pedido liberado!";
                        } else {
                            echo "2~3 dias úteis p/confirmação";
                        } ?>
                    </span>
                </div>
            </div>

            <div class="timeline-item timeline-<?php if ($order_status == "Concluído") { echo "success"; } elseif ($order_status == "Pagamento Realizado") {  echo "info"; } else { echo "default"; } ?>">
                <div class="timeline-number">03</div>
                <div class="timeline-info">
                    <strong>Separação e Despache</strong> <br>
                    <span>
                        <?php if ($order_status == "Concluído") { 
                            echo "pacote despachado";
                        } elseif ($order_status == "Pagamento Realizado") { 
                            echo "até 4 dias úteis";
                        } else {
                            echo "aguardando pagamento";
                        } ?>
                    </span>
                </div>
            </div>

            <div class="timeline-item timeline-<?php if ($order_status == "Concluído") { echo "success"; } else {  echo "default"; } ?>">
                <div class="timeline-number">04</div>
                <div class="timeline-info">
                    <strong>Entrega</strong> <br>
                    <span>
                        <?php if ($order_status == "Concluído") { 
                            echo "pedido em transporte!";
                        } else { 
                            echo "aguardando despache";
                        } ?>
                    </span>
                </div>
            </div>
            <?php elseif ($order_status == "Cancelado"): ?>
                <div class="timeline-item timeline-danger">
                    <div class="timeline-number">02</div>
                    <div class="timeline-info">
                        <strong>Cancelado</strong> <br>
                        <span><?php echo $this->__('Help? Contact'); ?> <a href="<?php echo Mage::getUrl('contato'); ?>"><?php echo $this->__('Support'); ?></a></span>
                    </div>
                </div>
            <?php elseif ($order_status == "Em Espera"): ?>
                <div class="timeline-item timeline-info">
                    <div class="timeline-number">02</div>
                    <div class="timeline-info">
                        <strong>Em Espera</strong> <br>
                        <span><?php echo $this->__('Help? Contact'); ?> <a href="<?php echo Mage::getUrl('contato'); ?>"><?php echo $this->__('Support'); ?></a></span>
                    </div>
                </div>
            <?php elseif ($order_status == "Fechado"): ?>
                <div class="timeline-item timeline-success">
                    <div class="timeline-number">02</div>
                    <div class="timeline-info">
                        <strong>Fechado</strong> <br>
                        <span>Reembolso Realizado</span>
                    </div>
                </div>
            <?php endif ?>
        </div>
    </div>

    <div class="row order-details-info">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <h1><?php echo $this->__('Order'), ' #', $order_id ?></h1>
            <span class="order-label order-label-default">
                <?php echo $order_status; ?>
            </span>
            <p class="order-date">
                <?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?>
            </p>
            <?php echo $this->getChildHtml('buttons') ?>
            <?php echo $this->getStatusHistoryRssUrl($_order) ?>

            <?php if (!$_order->getIsVirtual()): ?>
                <div class="box box-shipping">
                    <div class="box-title">
                        <h3><?php echo $this->__('Shipping Method') ?></h3>
                    </div>
                    <div class="box-content">
                        <?php if ($_order->getShippingDescription()): ?>
                            <div class="box-shipping-content">
                                <span class="shipping-flag <?php echo $order_shipping; ?>"></span>
                                <strong><?php echo $order_shippingTitle; ?></strong>
                            </div>
                            <?php if ($_order->getTracksCollection()->count()) : ?>
                                <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_order) ?>','trackorder','top=0,left=0,width=800,height=600,resizable=yes,scrollbars=yes'); return false;" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Track your order')) ?>" data-toggle="tooltip" data-placement="bottom" class="btn btn-default"><span class="fa fa-left fa-truck"></span><?php echo $this->__('Track your order') ?></a>
                            <?php else: ?>
                                <span class="waiting-track">Aguardando...</span>
                            <?php endif; ?>
                        <?php else: ?>
                            <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
            <div class="box box-payment">
                <div class="box-title">
                    <h3><?php echo $this->__('Payment Method') ?></h3>
                </div>
                <div class="box-content">
                    <div class="box-payment-content">
                        <span class="payment-flag <?php echo $order_paymentCode; ?>"></span>
                        <?php echo $this->getPaymentInfoHtml(); ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3><?php echo $this->__('Billing Address') ?></h3>
                </div>
                <div class="panel-body">
                    <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
                </div>
            </div>

            <?php if (!$_order->getIsVirtual()): ?>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3><?php echo $this->__('Shipping Address') ?></h3>
                    </div>
                    <div class="panel-body">
                        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
