<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php $_helper  = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view">
    <?php echo $this->getMessagesBlock()->toHtml() ?>
</div>
<div class="product-view">
    <div class="product-essential">
        <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>
            <div class="product-shop">
                <div class="product-sku">
                    <span><?php echo $this->__('SKU') ?>:</span> <?php echo $_product->getData('sku'); ?></span>
                </div>

                <div class="product-name">
                    <?php $_productName = $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                    <h1><span><?php echo $_productName ?></span></h1>
                </div>

                <?php echo $this->getChildHtml('alert_urls') ?>

                <?php echo $this->getChildHtml('product_type_data') ?>

                <?php echo $this->getChildHtml('extrahint') ?>

                <?php echo $this->getChildHtml('product.info.payment') ?>

                <?php //echo $this->getChildHtml('shipping.estimate.form') ?>

                <?php if ($_product->getShortDescription()):?>
                    <div class="short-description">
                        <h2><?php echo $this->__('Quick Overview') ?></h2>
                        <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                    </div>
                <?php endif;?>

                <?php if (!$this->hasOptions() && $_product->isSaleable()): ?>                
                    <div class="add-to-box">
                        <?php echo $this->getChildHtml('addtocart') ?>
                    </div>
                    <?php echo $this->getChildHtml('extra_buttons') ?>
                <?php endif; ?>

                <?php echo $this->getChildHtml('other');?>

                <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>

                <div class="row between-xs">
                    <div class="col-xs-5">
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>

                    <div class="col-xs">
                        <?php echo $this->getChildHtml('product.info.share') ?>
                    </div>
                </div>
            </div>

            <div class="product-img-box">
                <?php echo $this->getChildHtml('media') ?>
            </div>

            <div class="clearer"></div>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
        </form>
    
        <script type="text/javascript">
        //<![CDATA[
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function(button, url) {
                if (this.validator.validate()) {
                    var form = this.form;
                    var oldUrl = form.action;

                    if (url) {
                       form.action = url;
                    }
                    var e = null;
                    try {
                        this.form.submit();
                    } catch (e) {
                    }
                    this.form.action = oldUrl;
                    if (e) {
                        throw e;
                    }

                    if (button && button != 'undefined') {
                        button.disabled = true;
                    }
                }
            }.bind(productAddToCartForm);

            productAddToCartForm.submitLight = function(button, url){
                if(this.validator) {
                    var nv = Validation.methods;
                    delete Validation.methods['required-entry'];
                    delete Validation.methods['validate-one-required'];
                    delete Validation.methods['validate-one-required-by-name'];
                    // Remove custom datetime validators
                    for (var methodName in Validation.methods) {
                        if (methodName.match(/^validate-datetime-.*/i)) {
                            delete Validation.methods[methodName];
                        }
                    }

                    if (this.validator.validate()) {
                        if (url) {
                            this.form.action = url;
                        }
                        this.form.submit();
                    }
                    Object.extend(Validation.methods, nv);
                }
            }.bind(productAddToCartForm);
        //]]>
        </script>
    </div>

    <div class="product-content">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-5 col-lg-5">
                <?php echo $this->getChildHtml('product.attributes') ?>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-7 col-lg-7">
                <?php
                    $_video = $_product->getData('video');
                    if($_video != ""):
                ?>
                    <h2><?php echo $this->__("Video") ?></h2>
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="<?php echo 'https://www.youtube.com/embed/' . $_video ?>"></iframe>
                    </div>
                <?php endif ?>

                <?php echo $this->getChildHtml('product.description') ?>

                <div class="product-collateral toggle-content tabs">
                    <?php if ($detailedInfoGroup = $this->getChildGroup('detailed_info', 'getChildHtml')):?>
                        <dl id="collateral-tabs" class="collateral-tabs">
                            <?php foreach ($detailedInfoGroup as $alias => $html):?>
                                <?php //echo $this->escapeHtml($this->getChildData($alias, 'title')) ?>
                                <div class="tab-content"><?php echo $html ?></div>
                            <?php endforeach;?>
                        </dl>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>

    <?php echo $this->getChildHtml('upsell_products') ?>
    <?php echo $this->getChildHtml('product_additional_data') ?>
</div>
