<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div id="onestepcheckout-address-billing" class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
        <ul class="form-list row">

            <?php if($this->isCustomerLoggedIn() && Mage::getStoreConfig('onestepcheckout/general/is_show_titles')) : ?>
                <li class="osc-title col-xs-12"><?php echo $this->__('Billing Address') ?></li>
            <?php endif ?>

            <?php if ($this->customerHasAddresses()): ?>
                <li class="col-xs-12">
                    <label for="billing-address-select" class="required"><em>*</em><?php echo $this->__('Select a address') ?></label>
                    <div class="input-box">
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                </li>
            <?php endif; ?>

            <li class="col-xs-12">
                <ul id="onestepcheckout-billing-address-list" class="row" <?php if ($this->customerHasAddresses()): ?> style="overflow: hidden;height: 0px;display:none"<?php endif; ?>>
                
                    <?php if (!$this->isCustomerLoggedIn()) : ?>
                        <?php if(Mage::getStoreConfig('onestepcheckout/general/is_show_titles')): ?>
                            <li class="col-xs-12 osc-title">
                                <?php echo $this->__('Access Information') ?>
                            </li>
                        <?php endif; ?>

                        <li class="col-xs-12">
                            <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
                            <div class="input-box">
                                <input type="text" name="billing[email]" id="billing:email" title="<?php echo $this->__('Email') ?>" class="input-text validate-email validate-email-exist required-entry" value="<?php echo $this->getDataFromSession('email'); ?>" />
                            </div>
                        </li>
                        
                        <li class="col-xs-12">
                            <ul id="osc-billing-password-area" style="overflow: hidden;<?php if (!$this->getDataFromSession('create_account') && $this->customerMustBeRegistered()): ?>height: 0px;display:none<?php endif; ?>">
                                <li class="fields">
                                    <div class="field">
                                        <label for="billing:customer_password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                                        <div class="input-box">
                                            <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                                        </div>
                                    </div>
                                    <div class="field">
                                        <label for="billing:confirm_password" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                                        <div class="input-box">
                                            <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                        <li class="col-xs-12">
                            <?php if ($this->customerMustBeRegistered()): ?>
                                <div class="control">
                                    <input type="checkbox" name="billing[create_account]" value="1" title="<?php echo $this->__('Create Account') ?>" id="billing:create_account" class="checkbox"<?php if ($this->getDataFromSession('create_account')): ?> checked="checked"<?php endif; ?>/>
                                    <label for="billing:create_account"><?php echo $this->__('Create Account') ?></label>
                                </div>
                            <?php else: ?>
                                <input type="hidden" name="billing[create_account]" value="1" id="billing:create_account" />
                            <?php endif ?>
                        </li>
                    <?php endif ?>

                    <?php ## tipo pessoa ?>
                    <?php if (!$this->isCustomerLoggedIn()) : ?>
                        <?php if(Mage::getStoreConfig('onestepcheckout/general/is_show_titles')): ?>
                            <li class="osc-title col-xs-12">
                                <?php echo $this->__('Personal Information') ?>        
                            </li>
                        <?php endif; ?>

                        <?php $_tipopessoa = $this->getLayout()->createBlock('onestepcheckout/widget_tipopessoa') ?>
                        <?php if ($_tipopessoa->isEnabled()): ?>
                            <li class="col-xs-12 tipopessoa">
                                <div class="control">
                                    <input type="radio" name="billing[radio_tipopessoa]" value="Física" id="billing:fisica" class="radio" title="CPF" <?php if ($this->getDataFromSession('radio_tipopessoa') == 'Física'): ?> checked="checked"<?php endif; ?>/>
                                    <label for="billing:fisica"><?php echo $this->__('Pessoa Física') ?></label>
                                </div>
                                <div class="control">
                                    <input type="radio" name="billing[radio_tipopessoa]" value="Jurídica" id="billing:juridica" class="radio" title="CNPJ" <?php if ($this->getDataFromSession('radio_tipopessoa') == 'Jurídica'): ?> checked="checked"<?php endif; ?>/>
                                    <label for="billing:juridica"><?php echo $this->__('Pessoa Jurídica') ?></label>
                                </div>
                            </li>
                            <li class="wide hidden">
                                <?php echo $_tipopessoa->setTipopessoa($this->getDataFromSession('tipopessoa'))->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </li>
                        <?php endif ?>
                    <?php endif ?>

                    <?php ## name ?>
                    <li class="name-group">
                        <?php echo $this->getCustomerWidgetName()->toHtml(); ?>
                    </li> 

                    <?php ## TAX vat ?>
                    <?php if (!$this->isCustomerLoggedIn()): ?>
                        <?php if ($this->isTaxvatEnabled()): ?>
                            <li class="col-xs-6">
                                <?php echo $this->getTaxvatHtml() ?>
                            </li>
                        <?php endif; ?>
                        <?php $_ie = $this->getLayout()->createBlock('onestepcheckout/widget_ie') ?>
                        <?php if ($_ie->isEnabled()): ?>
                            <li class="col-xs-6">
                                <?php echo $_ie->setIe($this->getQuote()->getCustomerIe())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </li>
                        <?php endif ?>
                        <li id="osc-billing-tipopessoa-area" class="row clearfix" style="overflow: hidden;display:block;">
                            <div class="col-xs-6">
                                <?php $_dateOfBirthWidget = $this->getCustomerWidgetDateOfBirth(); ?>
                                <?php if ($_dateOfBirthWidget->isEnabled()): ?>
                                    <?php echo $_dateOfBirthWidget->toHtml() ?>
                                <?php endif; ?>
                            </div>
                            <div class="col-xs-6">
                                <?php $_genderWidget = $this->getCustomerWidgetGender(); ?>
                                <?php if ($_genderWidget->isEnabled()): ?>
                                    <?php echo $_genderWidget->toHtml() ?>
                                <?php endif ?>                                    
                            </div>
                        </li>
                    <?php endif; ?>

                    <?php ## phone ?>
                    <li class="col-xs-12">
                        <div class="row">
                            <div class="col-xs-6">
                                <label for="billing:telephone" class="required">
                                    <em>*</em><?php echo $this->__('Fax') ?>
                                </label>
                                <div class="input-box">
                                    <div class="input-group">
                                        <input type="text" name="billing[telephone]" title="<?php echo $this->__('Telephone') ?>" class="form-control input-text validate-phone-br <?php echo $this->getAttributeValidationClass('Telephone') ?>" id="billing:telephone" value="<?php echo $this->getDataFromSession('telephone'); ?>" placeholder="(XX) xxxx-xxxx" />
                                        <span class="input-group-btn">
                                            <a href="javascript:void(0)" class="btn btn-default whats-on" data-toggle="tooltip" title="Whatsapp?">
                                                <span class="fa fa-whatsapp"></span>
                                            </a>
                                        </span>
                                    </div>
                                </div> 
                            </div>   

                            <?php if ($this->getConfig()->isFax()): ?>
                                <div class="col-xs-6">
                                    <label for="billing:fax">
                                        <?php echo $this->__('Telephone') ?>
                                    </label>
                                    <div class="input-box">
                                        <input type="text" name="billing[fax]" title="<?php echo $this->__('Fax') ?>" class="input-text validate-phone-br <?php echo $this->getAttributeValidationClass('Fax') ?>" id="billing:fax" value="<?php echo $this->getDataFromSession('fax'); ?>"  placeholder="(XX) xxxxx-xxxx" />
                                    </div>
                                </div>
                            <?php endif; ?>
                        </div>
                    </li>

                    <?php if (!$this->isCustomerLoggedIn()): ?>
                </ul>
            </div>

            <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                <ul class="form-list row">
                    <?php endif; ?>

                    <?php if(!$this->isCustomerLoggedIn() && Mage::getStoreConfig('onestepcheckout/general/is_show_titles')): ?>
                        <li class="osc-title col-xs-12"><?php echo $this->__('Billing Address') ?></li>
                    <?php endif; ?>

                    <?php ## ZIP code ?>
                    <li class="col-xs-6">
                        <div class="form-group">
                            <label for="billing:postcode" class="required">
                                <em>*</em><?php echo $this->__('Zip/Postal Code') ?>
                            </label>
                            <div class="input-box input-group">
                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" class="input-text form-control validate-number <?php echo $this->getAttributeValidationClass('postcode') ?>" value="<?php echo $this->getDataFromSession('postcode') ?>" maxlength="8" onblur="buscaCep('billing');" />
                                <div class="onestepcheckout-postcod-process onestepcheckout-overlay-16">&nbsp;</div>
                                <span class="input-group-btn">
                                    <button class="btn btn-default" onclick="popWin('http://www.buscacep.correios.com.br/sistemas/buscacep/', 'I forgot my zipcode', 'width=360,height=370,left=200,top=50,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" type="button" data-toggle="tooltip" title="Qual o meu CEP?"><span class="fa fa-question"></span></button>
                                </span>
                            </div>
                        </div>
                    </li>

                    <?php ## Country ?>
                    <li class="col-xs-6">
                        <label for="billing:country_id" class="required">
                            <em>*</em><?php echo $this->__('Country') ?>
                        </label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect('billing') ?>
                        </div>
                    </li>

                    <?php ## Street ?>
                    <li class="col-xs-12">
                        <div class="row">
                        <?php $_streetValidationClass = $this->getAttributeValidationClass('street'); ?>
                        <?php $streetValues = $this->getDataFromSession('street'); ?>
                            <div class="col-xs-8">
                                <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" class="input-text <?php echo $_streetValidationClass ?>" value="<?php echo (isset($streetValues[0])) ? $streetValues[0] : ''; ?>" autocomplete="off"/>
                                </div>
                            </div>
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="wide <?php switch ($_i) {
                                    case 2: echo "col-xs-4"; break;
                                    case 3: echo "col-xs-6"; break;
                                    case 4: echo "col-xs-6"; break; }?>">
                                <label for="billing:street<?php echo $_i ?>" <?php if ($_i != 3): ?> class="required" <?php endif; ?>><?php if ($_i != 3): ?> <em>*</em> <?php endif; ?><?php echo $this->__('Street Address ' . $_i) ?></label>
                                <div class="input-box">
                                    <input type="text" title="<?php echo $this->__('Street Address ' . $_i) ?>" name="billing[street][<?php echo $_i ?>]" id="billing:street<?php echo $_i ?>" class="input-text <?php if ($_i != 3): ?>required-entry<?php endif; ?>" value="<?php echo $streetValues[$_i]; ?>" autocomplete="off"/>
                                </div>
                            </div>
                        <?php endfor; ?>
                        </div>
                    </li>

                    <?php ## City ?>
                    <li class="col-xs-6">
                        <label for="billing:city" class="required">
                            <em>*</em><?php echo $this->__('City') ?>
                        </label>
                        <div class="input-box">
                            <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" class="input-text <?php echo $this->getAttributeValidationClass('city') ?>" id="billing:city" value="<?php echo $this->getDataFromSession('city') ?>" />
                        </div>
                    </li>

                    <?php ## State  ?>
                    <li class="col-xs-6">
                        <label for="billing:region_id" class="required">
                            <em>*</em><?php echo $this->__('State/Province') ?>
                        </label>
                        <div class="input-box">
                            <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                                //<![CDATA[
                                $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getDataFromSession('region_id') ?>");
                                //]]>
                            </script>
                            <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->getAttributeValidationClass('region') ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </li>

                    <?php ## Company ?>
                    <?php if ($this->getConfig()->isCompany()): ?>
                        <li class="col-xs">
                            <label for="billing:company"><?php echo $this->__('Company') ?></label>
                            <div class="input-box">
                                <input type="text" id="billing:company" name="billing[company]" title="<?php echo $this->__('Company') ?>" class="input-text <?php echo $this->getAttributeValidationClass('company') ?>" value="<?php echo $this->getDataFromSession('company'); ?>" />
                            </div>
                        </li>
                    <?php endif; ?>

                    <?php ## VAT number [?] ?>
                    <?php if ($this->isVatAttributeVisible()) : ?>
                        <li class="col-xs">
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                            <div class="input-box">
                                <input type="text" id="billing:vat_id" name="billing[vat_id]" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo $this->getAttributeValidationClass('vat_id'); ?>" value="<?php echo $this->getDataFromSession('vat_id'); ?>" />
                            </div>
                        </li>
                    <?php endif; ?>

                    <?php ## [logged] save in address book ?>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                        <li class="col-xs-12">
                            <div class="control">
                                <input type="checkbox" name="billing[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book" onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getDataFromSession('save_in_address_book')): ?> checked="checked"<?php endif; ?> class="checkbox" />
                                <label for="billing:save_in_address_book"><?php echo $this->__('Save in address book') ?></label>
                            </div>
                        </li>
                    <?php else: ?>
                        <li class="no-display"><input type="hidden" name="billing[save_in_address_book]" value="1" /></li>
                    <?php endif; ?>

                    <?php if ($this->isCustomerLoggedIn()): ?>
                </ul>
            </div>
            <?php endif ?>
        </ul>
    </li>

<?php if ($this->isCustomerLoggedIn()): ?>
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
<?php endif ?>
        <ul class="form-list row">
            <?php if (!$this->isUseBillingAsShipping() && $this->canShip()): ?>
                <?php if(Mage::getStoreConfig('onestepcheckout/general/is_show_titles')): ?>
                    <li class="col-xs-12 osc-title">
                        <?php echo $this->__('Shipping Address') ?>
                    </li>
                <?php endif; ?>

                <?php if ($this->isCustomerLoggedIn()): ?>
                    <li class="col-xs-12 hidden">
                        <div class="control">
                            <input type="checkbox" name="billing[use_for_shipping]" value="1" title="<?php echo $this->__('Ship to same address') ?>" id="billing:use_for_shipping" class="checkbox" />
                            <label for="billing:use_for_shipping"><?php echo $this->__('Ship to same address') ?></label>
                        </div>
                    </li>
                <?php else: ?>
                    <li class="col-xs-12">
                        <div class="control">
                            <input type="checkbox" name="billing[use_for_shipping]" value="1" title="<?php echo $this->__('Ship to same address') ?>" id="billing:use_for_shipping" <?php if ($this->isUseBillingAsShippingChecked()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                            <label for="billing:use_for_shipping"><?php echo $this->__('Ship to same address') ?></label>
                        </div>
                    </li>
                <?php endif; ?>

            <?php else : ?>
                <li class="no-display"><input type="hidden" name="billing[use_for_shipping]" value="1" /></li>
            <?php endif; ?>

            <?php ## [block] Shipping Address
                  ## move using JS ?>
            <div id="onestepcheckout-address-shipping-wrapper-body" class="col-xs-12"></div>
        </ul>          
    </div>
<?php echo $this->getChildHtml('extra'); ?>

<script type="text/javascript">
    //<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    <?php if (!$this->isCustomerLoggedIn()) : ?>
        $$("input[name*='radio_tipopessoa']").invoke('on', 'click', function() {
            var sel = $('billing:tipopessoa');
            setTipopessoaArea(this.value);
            for (var i = 0; i < sel.options.length; i++) {
                if (sel.options[i].text == this.value) {
                    sel.options[i].selected = true;
                }
            }

        });
        function setTipopessoaArea(arg){

            if (arg == 'Jurídica') {
                if ($('billing:taxvat')) {
                    $('billing:taxvat').maxLength = 18;
                    $('billing:ie').maxLength = 30;
                    $$('label[for="billing:ie"]').first().update('Inscrição Estadual');
                    $$('label[for="billing:taxvat"]').first().update('CNPJ <em>*</em>');
                    $$('label[for="billing:firstname"]').first().update('Razão social <em>*</em>');
                    $$('label[for="billing:lastname"]').first().update('None Fantasia <em>*</em>');
                    $('osc-billing-tipopessoa-area').hide();
                }
            } else {
                if ($('billing:taxvat')) {
                    $('billing:taxvat').maxLength = 14;
                    $('billing:ie').maxLength = 30;
                    $$('label[for="billing:taxvat"]').first().update('CPF <em>*</em>');
                    $$('label[for="billing:ie"]').first().update('RG');
                    $$('label[for="billing:firstname"]').first().update('Nome <em>*</em>');
                    $$('label[for="billing:lastname"]').first().update('Sobrenome <em>*</em>');
                    $('osc-billing-tipopessoa-area').show();
                }
            }
        }
        <?php if (is_null($this->getDataFromSession('radio_tipopessoa'))): ?>
            $$('[name*=billing[radio_tipopessoa]]')[0].click();
        <?php else: ?>
            if ($('billing:tipopessoa')) {
                setTipopessoaArea('<?php echo $this->getDataFromSession('radio_tipopessoa') ?>');
            }
        <?php endif; ?>
    Validation.add('validate-email-exist', '<?php echo $this->__('Please enter a valid email address. For example johndoe@domain.com.') ?>', function(value) {
        if (checkMail(value)) {
            var ok = false;
            var url = BASE_URL + 'onestepcheckout/ajax/check_email/';
            new Ajax.Request(url, {
                method: 'post',
                asynchronous: false,
                parameters: 'email=' + encodeURIComponent(value),
                onSuccess: function(transport) {
                    var obj = response = eval('(' + transport.responseText + ')');
                    validateTrueEmailMsg = obj.status_desc;
                        if (obj.result !== 'clean') {
                            Validation.get('validate-email-exist').error = 'Email já cadastrado';
                                ok = false;
                        } else {
                                ok = true;
                        }
                    },
                    onComplete: function() {
                        if ($('advice-validate-email-exist-billing:email')) {
                          $('advice-validate-email-exist-billing:email').remove();
                        }
                    }
                });
            return ok;
        }else{
            Validation.get('validate-email').error = '<?php echo $this->__('Please enter a valid email address. For example johndoe@domain.com.') ?>';
        }
    });
    Validation.add('validate-taxvat', '<?php echo $this->__('This is a required field.') ?>', function(value) {
        if (validaCPF(value,0)) {
            var ok = false;
            var url = BASE_URL + 'onestepcheckout/ajax/check_taxvat/';
            new Ajax.Request(url, {
                method: 'post',
                asynchronous: false,
                parameters: 'taxvat=' + encodeURIComponent(value),
                onSuccess: function(transport) {
                    var obj = response = eval('(' + transport.responseText + ')');
                    validateTrueEmailMsg = obj.status_desc;
                    if (obj.result !== 'clean') {
                        Validation.get('validate-taxvat').error = 'CPF/CNPJ já cadastrado';
                            ok = false;
                    } else {
                            ok = true;
                    }
                },
                onComplete: function() {
                    if ($('advice-validate-taxvat-billing:taxvat')) {
                        $('advice-validate-taxvat-billing:taxvat').remove();
                    }
                }
            });
            return ok;
         }else{
                 Validation.get('validate-taxvat').error = 'O CPF/CNPJ informado \xE9 inválido';
         }
    });
    <?php endif; ?>
    Validation.add('validate-zip-br', '<?php echo $this->__('Please enter a valid zip code. e.g. 12345678.') ?>', function(v) {
        return Validation.get('IsEmpty').test(v) || /(^\d{8}$)|(^\d{5}-\d{3}$)/.test(v);
    });
    Validation.add('validate-phone-br', '<?php echo $this->__('Please enter a valid phone number. for example, (xx) x4567-8900.') ?>', function(v) {
        return Validation.get('IsEmpty').test(v) || /^(\()?\d{2}(\))?(-|\s)?\d{5}(-|\s)\d{4}|(\()?\d{2}(\))?(-|\s)?\d{4}(-|\s)\d{4}$/.test(v);
    });
    
    if ($('billing:taxvat')) {
        $('billing:taxvat').addClassName('validate-taxvat');
        $('billing:taxvat').observe('keyup', function(event) {
            mascara(this, mdocumento);
        });
    }
    
    if ($('billing:telephone')) {
        $('billing:telephone').addClassName('validate-phone-br');
        $('billing:telephone').observe('keyup', function(event) {
            this.maxLength = 15;
            mascara(this, mtel);
        });
    }
    if ($('billing:fax')) {
        $('billing:fax').addClassName('validate-phone-br');
        $('billing:fax').observe('keyup', function(event) {
            this.maxLength = 15;
            mascara(this, mtel);
        });
    }
    if ($('billing:postcode')) {
        $('billing:postcode').addClassName('validate-zip-br');
        $('billing:postcode').observe('keyup', function(event) {
            this.maxLength = 8;
            mascara(this, sonumeros);
        });
    }
    if ($('billing:street1')) {
        $('billing:street1').observe('keyup', function(event) {
            this.maxLength = 40;
        });
    }
    if ($('billing:street2')) {
        $('billing:street2').observe('keyup', function(event) {
            this.maxLength = 5;
        });
    }
    if ($('billing:street3')) {
        $('billing:street3').observe('keyup', function(event) {
            this.maxLength = 20;
        });
    }
    if ($('billing:street4')) {
        $('billing:street4').observe('keyup', function(event) {
            this.maxLength = 20;
        });
    }
    if ($('billing:city')) {
        $('billing:city').observe('keyup', function(event) {
            this.maxLength = 30;
        });
    }
    if ($('billing:day')) {
        $('billing:day').observe('keyup', function(event) {
            this.maxLength = 2;
            mascara(this, sonumeros);
        });
        $('billing:month').observe('keyup', function(event) {
            this.maxLength = 2;
            mascara(this, sonumeros);
        });
        $('billing:year').observe('keyup', function(event) {
            this.maxLength = 4;
            mascara(this, sonumeros);

        });
    }
    //]]>
</script>
