<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php if($this->getItemCount()): ?>
<div class="crosssell">
    <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    <ul class="products-grid" id="crosssell-products-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
            <div class="item-box">
                <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(420) ?>" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
                <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                <?php echo $this->getReviewsSummaryHtml($_item) ?>

                <?php if ($_item->isGrouped()):
                    $_associatedProducts = $_item->getTypeInstance(true)->getAssociatedProducts($_item); 
                    $prices = [];
                    $grouped_price = 0;
                    $price_difference = 0;

                    foreach($_associatedProducts as $_product) {
                        $id = $_product->getId();
                        $product = Mage::getModel('catalog/product')->load($id);

                        $prices[] = $product['price'];

                        if ($product['special_price']) {
                            $grouped_price += $product['special_price'];
                            $price_difference += $product['price']-$product['special_price'];
                        } else {
                            $grouped_price += $product['price'];
                        }
                    }

                    arsort($prices); // get highest price
                    $price_array = array_keys($prices);
                    $highest_price = $prices[$price_array[0]]; 
                ?>

                    <?php //echo $this->__('Highest price:') ?>
                    <?php //echo Mage::helper('core')->currency($highest_price) ?>

                    <div class="price-box">
                        <span class="regular-price">
                            <?php //echo $this->__('Total price for all these products:') ?>
                            <span class="price"><?php echo Mage::helper('core')->currency($grouped_price) ?></span>
                        </span>
                    </div>

                    <?php if ($price_difference): ?>
                        <?php //echo $this->__('Total save with all these products:') ?>
                        <?php //echo Mage::helper('core')->currency($price_difference) ?>
                    <?php endif; ?>

                <?php else: ?>
                    <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                <?php endif; ?>

                <?php if ($_item->isGrouped()):
                    $_finalPrice  = $grouped_price; else:
                    $_finalPrice  = $_item->getFinalPrice();
                endif; ?>

                <ul class="price-new">
                    <?php
                        $_plots = $_item->getData('price_plots');
                        $_plots_tax = $_item->getData('plots_tax');
                        if($_plots != ""):
                    ?>
                        <li class="price-plots-block">
                            <?php echo '<strong> '.$_plots .'x '.$this->__('of').' '.$this->helper('core')->currency(($_finalPrice * $_plots_tax) + $_finalPrice / $_plots, true, false).' '.$this->__('interest-free').'</strong>' ?>
                        </li>
                    <?php endif; ?>
                    <?php
                        $_barcode     = $_item->getData('discount_barcode');
                        $_calcBarcode = ($_barcode / 100) * $_finalPrice;
                        $_calcFinal   = $this->helper('core')->currency($_finalPrice - $_calcBarcode, true, false);
                        if($_barcode != ""):
                    ?>
                        <li class="price-barcode-block">
                            <strong class="barcode-price-label"><?php echo $_barcode.'% '.' off '.$this->__('via barcode');  ?></strong>
                            <span class="special-price barcode-price"><span class="price"><?php echo $_calcFinal; ?></span></span>
                        </li>
                    <?php endif; ?>
                </ul>

                <div class="actions">
                    <?php if($_item->isSaleable()): ?>
                        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php echo Mage::helper('netgo_gwishlist')->getUrl($_item); ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                            <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>        
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif; ?>
