<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php $_wishlistSubmitUrl = $this->helper('wishlist')->getAddUrl($_product); ?>

<ul class="add-to-links">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <li><a href="<?php echo $_wishlistSubmitUrl ?>" onclick="productAddToCartForm.submitLight(this, this.href); return false;" class="link-wishlist" data-toggle="tooltip" title="<?php echo $this->__('Add to Wishlist') ?>"><span class="hidden-md hidden-lg"><?php echo $this->__('Wishlist') ?></span><span class="hidden-xs hidden-sm"><?php echo $this->__('Add to Wishlist') ?></span></a></li>
<?php endif; ?>
</ul>
