<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php  $_order = $this->getOrder() ?>
<?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
    <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="link-rss f-none"><?php echo $this->__('Subscribe to Order Status') ?></a>
<?php endif; ?>
<?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
    <a href="<?php echo $this->getReorderUrl($_order) ?>" class="btn btn-default"><span class="fa fa-left fa-retweet"></span><?php echo $this->__('Reorder') ?></a>
<?php endif ?>
<?php echo $this->getChildHtml(); ?>
