<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php
/* @var $this Mage_Wishlist_Block_Customer_Wishlist_Item_Column_Cart */
/* @var Mage_Wishlist_Model_Item $item */
$item = $this->getItem();
$product = $item->getProduct();
$options = $this->getChild('customer.wishlist.item.options')
    ->setItem($item)
    ->getConfiguredOptions();
?>
<div class="prixe-box">
    <?php echo $this->getPriceHtml($product, empty($options));?>
</div>
<div class="actions">
    <?php if ($product->isSaleable()): ?>
        <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" onclick="addWItemToCart(<?php echo $item->getId()?>);" class="button btn-cart">
            <span><span><?php echo $this->__('Add to Cart') ?></span></span>
        </button>
    <?php else: ?>
        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
    <?php endif; ?>

    <ul class="add-to-links">
        <li>
            <a class="btn-edit" data-toggle="tooltip" data-placement="bottom" title="<?php echo $this->__('Edit') ?>" href="<?php echo $this->getItemConfigureUrl($item) ?>"><?php echo $this->__('Edit') ?></a>
        </li>
        <li>
            <a href="<?php echo $this->getItemRemoveUrl($this->getItem()); ?>" onclick="return confirmRemoveWishlistItem();" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove Item')) ?>" data-toggle="tooltip" data-placement="bottom" class="btn-remove btn-remove2"><?php echo $this->__('Remove item');?></a>
        </li>
        <?php foreach($this->getSortedChildren() as $childName):?>
            <?php echo $this->getChildHtml($childName, false);?>
        <?php endforeach;?>
    </ul>
</div>
