<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<header class="default">
    <div class="header-top">
        <div class="container">
            <div class="row clean visible-xs">
                <div class="action-list">
                    <?php // Wishlist block ?>
                    <?php if($this->helper('wishlist')->isAllow()): ?>
                    <div class="action-item action-wishlist">
                        <div class="action-item-wrap">
                            <a href="javascript:void(0);" class="push-wishlist">
                                <span>
                                    <strong><?php echo $this->__('Wishlist'); ?></strong>
                                    <sup><?php echo $this->helper('wishlist')->getItemCount() ?></sup>
                                </span>
                            </a>
                        </div>
                    </div>
                    <?php endif; ?>

                    <?php // cart block ?>
                    <div class="action-item action-cart">
                        <div class="action-item-wrap">
                            <a href="javascript:void(0);" class="push-cart">
                                <span>
                                    <strong><?php echo $this->__('Cart'); ?></strong>
                                    <sup><?php echo Mage::helper('checkout/cart')->getCart()->getItemsCount(); ?></sup>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row hidden-xs">
                <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
                    <div class="row clean middle-xs">
                        <div class="welcome-msg">
                        <?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?>
                        </div>
                        <div class="about-links">
                            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('header_alt_links')->toHtml(); ?>
                        </div>
                    </div>
                </div>

                <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                    <div class="row clean middle-xs end-xs">
                        <?php echo $this->getChildHtml('currency_switcher') ?>
                        <?php echo $this->getChildHtml('store_language') ?>
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="header-middle">
        <div class="container">
            <div class="row middle-xs between-xs">

                <div class="col-xs-8 col-sm-4 col-md-3 col-lg-3">
                    <div class="logo">
                        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
                            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
                        </a>
                    </div>
                </div>

                <div class="hidden-xs hidden-sm col-md-offset-1 col-md-6 col-lg-offset-1 col-lg-6">
                    <?php echo $this->getChildHtml('topSearch') ?>
                </div>

                <div class="col-xs-4 col-sm-3 col-md-2 col-lg-2">
                    <div class="action-block">
                        <?php // Wishlist block ?>
                        <?php if($this->helper('wishlist')->isAllow()): ?>
                        <div class="action-item action-wishlist hidden-xs">
                            <div class="action-item-wrap">
                                <a href="javascript:void(0);" class="push-wishlist">
                                    <span>
                                        <strong><?php echo $this->__('Wishlist'); ?></strong>
                                        <sup><?php echo $this->helper('wishlist')->getItemCount() ?></sup>
                                    </span>
                                </a>
                          </div>
                        </div>
                        <?php endif; ?>
                        <?php // cart block ?>
                        <div class="action-item action-cart hidden-xs">
                            <div class="action-item-wrap">
                                <a href="javascript:void(0);" class="push-cart">
                                    <span>
                                        <strong><?php echo $this->__('Cart'); ?></strong>
                                        <sup><?php echo Mage::helper('checkout/cart')->getCart()->getItemsCount(); ?></sup>
                                    </span>
                                </a>
                            </div>
                        </div>

                        <div class="burger hidden-md hidden-lg">
                            <button class="hamburger hamburger--elastic" type="button" aria-label="Menu" aria-controls="navigation" aria-expanded="true/false">
                            <span class="hamburger-box">
                              <span class="hamburger-inner"></span>
                            </span>
                          </button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="header-bottom hidden-xs hidden-sm">
        <div class="container">
            <div class="row middle-xs">
                
                <div class="col-xs-8">
                    <div id="navbarPrimary" class="navbar navbar-dropdown">
                        <?php echo $this->getChildHtml('topMenu') ?>
                    </div>
                </div>

                <div class="col-xs-4">
                    <div class="navbar navbar-dropdown navbar-alt">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('navbar_alt')->toHtml() ?>
                    </div>
                </div>

            </div>
        </div>
    </div>
</header>

<div class="push-group">

    <div class="push-hidden-area"></div>
    
    <div id="pushNavbar" class="push-menu push-right">
        <div class="push-wrapper">
            <div class="push-section">
                <?php echo $this->getChildHtml('currency_switcher') ?>
                <?php echo $this->getChildHtml('store_language') ?>
                <?php echo $this->getChildHtml('topLinks') ?>
                <?php echo $this->getChildHtml('topSearch') ?>
            </div>
            <div class="push-section-nav">
                <div class="navbar navbar-collapse">
                    <?php echo $this->getChildHtml('topMenu') ?>
                </div>
            </div>
            <div class="push-section-nav-alt">
                <div class="navbar navbar-collapse navbar-alt">
                    <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('navbar_alt')->toHtml() ?>
                </div>
            </div>
        </div>
    </div>

    <div id="pushCart" class="push-menu push-right">
        <div class="push-wrapper">
            <div class="push-section">
                <div class="row clean middle-xs between-xs push-title">
                    <h3><?php echo $this->__('My Cart') ?></h3>
                    <a href="javascript:void(0);" class="button push-close"><span><span><?php echo $this->__('Close') ?></span></span></a>
                </div>
            </div>
            <div class="push-section">
                <?php echo $this->getChildHtml('cart_header') ?>
            </div>
        </div>
    </div>

    <div id="pushWishlist" class="push-menu push-right">
        <div class="push-wrapper">
            <div class="push-section">
                <div class="row clean middle-xs between-xs push-title">
                    <h3><?php echo $this->__('Wishlist') ?></h3>
                    <a href="javascript:void(0);" class="button push-close"><span><span><?php echo $this->__('Close') ?></span></span></a>
                </div>
            </div>
            <div class="push-section">
                <?php 
                    if(!Mage::getSingleton('customer/session')->isLoggedIn()){
                        echo $this->getChildHtml('gwishlist_header');
                    }else{
                        echo $this->getChildHtml('wishlist_header');
                    }
                ?>
            </div>
        </div>
    </div>
</div>

<div class="slideshow-wrap"></div>

<?php echo $this->getChildHtml('topContainer'); ?>
