<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<meta name="viewport" content="width=device-width, initial-scale=1 ,maximum-scale=1, minimum-scale=1">
<meta charset="UTF-8">

<title><?php echo $this->getTitle() ?></title>

<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>">
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>">
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>">

<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
