<?php
/**
 *
 * @category    design
 * @package     magestrike_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Update Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <label for="qty" class="sr-only"><?php echo $this->__('Qty:') ?></label>
        <?php if (!$_product->isGrouped()): ?>
	    	<div>
	        	<div class="input-group input-group-lg">
		        	<div class="input-group-btn">
		        		<div class="dec qty-btn button">-</div>
		        	</div>
	        		<input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Qty')) ?>" class="input-text qty" />
		        	<div class="input-group-btn">
		        		<div class="inc qty-btn button">+</div>
		        	</div>
		        </div>
	        </div>
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
