<?php
/**
 *
 * @category    design
 * @package     magestack_default
 * @author      Wesley Almeida <wesleyalmd@gmail.com>
 *
 */
?>
<div class="product-options" id="product-options-wrapper">
    <?php if ($this->hasRequiredOptions()):?>
        <p class="required"><?php echo $this->__('Required Fields') ?></p>
    <?php endif;?>
    <?php echo $this->getChildHtml('', true, true);?>
</div>
<script type="text/javascript">decorateGeneric($$('#product-options-wrapper dl'), ['last']);</script>
